### ISSUE TITLE
Add drop down for multiple backups in the same directory

### ISSUE THREAD

**Issue by AE720** [rescuezilla/rescuezilla#109]
One thing that would look nice is if when choosing a backup, you weren't seeing all of the loose files that contain the data to the backup but rather the backup itself. I suggest that having a dropdown selection after clicking on a folder would be a nice idea. That dropdown showing the backup files only such as "062020" and "072020" instead of seeing the file that you have to know has the desired file extension, even if everything else is grayed out. Possibly even just present it in a list under the bar that has the folder icon you click on CHOOSE the directory where those backups exist.

**Comment by shasheene** [comment]
Yep, will do!

**Comment by shasheene** [comment]
As mentioned in #52, here's a sneak-peak of the mid-October 2020 Rescuezilla release implementing your suggestion:

 <a href="https://user-images.githubusercontent.com/1414379/93178518-830a2000-f773-11ea-8a20-69e99b1a9261.png"><img src="https://user-images.githubusercontent.com/1414379/93178518-830a2000-f773-11ea-8a20-69e99b1a9261.png" width="1280" height="1024"/></a>

**Comment by shasheene** [comment]
Fixed in [Rescuezilla v2.0](https://github.com/rescuezilla/rescuezilla/releases/latest).
