### ISSUE TITLE
Unable to find network share from Windows Server 2016 for backup

### ISSUE THREAD

**Issue by fredddii** [rescuezilla/rescuezilla#110]
I am unable to connect to a network share that is available on Windows Server 2016 without username or password. This network share can be accessed fine on Windows 10 computers via the File Explorer.

I have tried via hostname and IP to no avail. When using the IP address it seems to freeze for about five seconds before throwing out the error message on the screenshot.

The feature "SMB 1.0/CIFS File Sharing Support" is installed on the Windows Server 2016 machine.

<img src="https://user-images.githubusercontent.com/15217150/87176577-982d8300-c2da-11ea-9440-360025a0b5cb.jpg" alt="IMG_20200710_111959 1" width="156" height="208"> <img src="https://user-images.githubusercontent.com/15217150/87176514-8350ef80-c2da-11ea-90bf-0642f1e7aa00.jpg" alt="IMG_20200710_111934 1" width="208" height="156"> <img src="https://user-images.githubusercontent.com/15217150/87176524-8815a380-c2da-11ea-9453-e4fad0a78502.jpg" alt="IMG_20200710_111946 1" width="208" height="156">

**Comment by shasheene** [comment]
Hi @fredddii,

Thank you for attempting to use [Rescuezilla](https://github.com/rescuezilla/rescuezilla/releases/latest).

The SMB/CIFS client on Ubuntu 20.04 (which Rescuezilla v1.0.6.1 64-bit is based on) automatically tries the SMB3.1.1 protocol by default. **Given you have said you have "SMB 1.0/CIFS File Sharing Support" installed, please try populating the Version field with "1.0" (without quotes) and try again.**

Please first open a terminal and run `ping `192.168.100.116` to confirm your network is correctly configured and can contact the remote file server.

Sorry about the GUI [momentarily freezing](https://github.com/rescuezilla/rescuezilla/issues/48) when an SMB mount, this will be fixed in the next version of Rescuezilla (v1.0.7).

I also have some [ideas](https://github.com/rescuezilla/rescuezilla/issues/6#issuecomment-580057438) on how to improve the relatively poor usability of SMB/CIFS network shares that I will be implementing soon! (I am open to suggestions)

Please try out entering "1.0" in the version field and let me know it went!

**Comment by fredddii** [comment]
I was unable to achieve any results. I have tried 1.0, 1.1, 2.0, 2.1, 3.0 and 3.1. The device can be reached via ping.

I can not search the network via the file manager, nor can I attempt a SMB connection this way.

On Monday I will try to boot a live CD with the latest Ubuntu LTS to see if I can reach our Windows Server 2016 shared folder that way. I will post results in the evening.

![IMG_20200711_102554](https://user-images.githubusercontent.com/15217150/87228412-62070680-c3a1-11ea-967d-143d30d2af74.jpg)

![IMG_20200711_102612](https://user-images.githubusercontent.com/15217150/87228409-5d425280-c3a1-11ea-9a82-be16a6ebe09b.jpg)


![IMG_20200711_102631](https://user-images.githubusercontent.com/15217150/87228401-51ef2700-c3a1-11ea-9574-7eb0dfa7e038.jpg)


![IMG_20200711_102747](https://user-images.githubusercontent.com/15217150/87228398-4996ec00-c3a1-11ea-9d12-c3c910ec0c3d.jpg)

**Comment by shasheene** [comment]
On your first post, the mount command reports that there was "No such file or directory" when trying to connect to 192.168.100._114_. On your second post the mount command reports a "Permission denied" error when connecting to 192.168.100._116_. I am assuming the first IP address you posted wasn't a typo. Side note, you may wish to configure a hostname on your fileserver and/or a "static DHCP" binding on your router's DHCP server so your file server doesn't keep changing IP addresses regularly.

Given the "Permission denied" error in your second post, you might want to try populating the server field with the simplest UNC path (eg, `\\192.168.100.116\backup`) in case there's permission issues around the directory you're trying to navigate to.

As for your comment about the file manager, Ubuntu 20.04 uses GNOME Files (formerly called “nautilus”) which supports navigating to SMB/CIFS network shares using a "UNC path" such as `\\192.168.100.116\backup`.

Rescuezilla uses PCManFM (a file manager created by a programmer named "PCMan"), which does _not_ appear to support UNC paths. The behavior you’re after is available with PCManFM using `smb://192.168.100.116/backup` path, _but_ Rescuezilla v1.0.6.1 does not come with the dependencies for this. Fortunately it is very easy to install. Please open a terminal in Rescuezilla and run the following two commands:

```
apt-get update
apt-get install gvfs-backends gvfs-fuse
```

After this completes, open the file manager again and and typing `smb://192.168.100.116/backup`. This will bring up the file manager SMB/CIFS mount authentication prompt that you're looking for. I haven't yet thoroughly tested if there's any adverse interactions between Rescuezilla and an existing GVFS virtual filesystem mount of a SMB/CIFS share made through PCManFM, so please make sure you unmount this directory by clicking the eject icon before proceeding with any Rescuezilla operations. I will add the file manager dependencies so the next version of Rescuezilla can use PCManFM with `smb://` paths.

**Comment by fredddii** [comment]
I got it working now. I am now using an authenticated user to access the network share (which is also recommended by Microsoft, having public shared folders is not).

All I needed to do was enter the network location, username and password, and it went flawless from there on. It was a clean Windows 10 virtual machine, I did not need to mess with any SMB features or settings.

Thanks again for providing quick responses and attempts to aid. The ticket can be closed.

**Comment by shasheene** [comment]
OK, I am glad you got it working using an authenticated user. Weird that public shared folders aren't working. Since you're no longer intending on using guest authentication and support for older versions of SMB, you should immediately disable these functions in your Windows Server configuration.
