### ISSUE TITLE
Scanning for backup images is annoyingly slow

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#126]
Rescuezilla v2.0 introduced a user-interface element which displays the images present in the backup folder:

<a href="https://user-images.githubusercontent.com/1414379/96356380-f0272180-1134-11eb-8024-35a88b8d6429.png"><img src="https://user-images.githubusercontent.com/1414379/96356380-f0272180-1134-11eb-8024-35a88b8d6429.png" width="800"/></a>

Users have been [complaining](https://sourceforge.net/p/rescuezilla/discussion/discussion/thread/aeba4d8004/#b95f) that scanning process to generate this table takes too long:

> Starting the backup program after booting to linux desktop, it also takes more time than the older version, especially the part the program is trying to find out the folders of the backup drive, it almost stalled there ...

and another user writes:

> it takes a LOT longer to load from a network share. Says scanning for up to a minute where before it was almost instant.

These users raise a good point. In previous versions this step was instantaneous: users would use the Browse button and navigate directly to the image they want to select. But now, mounting the drive containing the images can cause the Rescuezilla to keep scanning for potentially a whole minute (depending on the number of backup images), for _both_ backup and restore operations.

The scan only searches the base folder of your drive and one level deep. **As an easy temporary workaround, you can place your backup image directory in a subfolder so it's not automatically scanned, and use the Browse button to go directly to the backup you want to restore (avoiding scanning backup images that you are not interested in).** This is of course not ideal -- it means users have to change how they use Rescuezilla (and how they arrange their backup image hard drive) because there is a feature that slows them down.

Potential proper solutions are:

1. Speedup the image folder scan by doing this in parallel
2. Improve the ability for a user to stop the scan by clicking the X button (currently the popup closes but the scan still continues)
3. Improve backup image scanning progress bar so that a user knows how long they will be waiting
4. No longer automatically scan the folder but have a button for the user to launch the scan

I am leaning towards implementing solutions 2 and 3. If things are taking too long being able to stop the scan and browse to the folder you care about should take away much of the criticism.

It would be ideal to make things faster by running these operations in parallel. During the development of Rescuezilla v2.0, I tried querying the drive state in parallel and it made things _slower_ (and the code much more complicated).

See also: Task #125 for "Rescuezilla v2.0 backup operations reportedly much slower than v1.0.6.1"

**Comment by shasheene** [comment]
Fixed in [Rescuezilla v2.1](https://github.com/rescuezilla/rescuezilla/releases/latest): users can now stop the image scan by clicking the X button, and the scanning popup displays the image that is being scanned.

These two fixes make it much easier for users to choose quickly cancel the scan and browse directly to the image they want, which resolves much of the slow scanning issue.

**Comment by Aarixx** [comment]
It would be nice if this was reevaluated. Having to know to hit the x button isn't very intuitive and using it in a semi-production environment where there's about 40 images takes a VERY long time and it stops the scan and only displays what is shown, if the image begins with the letter x, y, or z, then you pretty much have to wait for the scan. It's a fair workaround to manually enter the path, but it might be proper to do what other backup managers do and keep them in zipped files. I'm assuming the scanning is needed to tell what exactly the image is (Clonezilla, Redo image, etc) but I hope an alternative check could be possible. 

I already mentioned perhaps using checksum. The directory will keep a hidden file with the checksum and the information needed to proceed and the only scanning is to quickly see that there's no change in the checksum and to essentially a "Delta scan".
