### ISSUE TITLE
Portuguese Brazilian translation of the Rescuezilla

### ISSUE THREAD

**Issue by vinicioslc** [rescuezilla/rescuezilla#128]
I have made entire translation from three files requested on [page](https://github.com/rescuezilla/rescuezilla/wiki/Translations-HOWTO)

I'll keep on track until be included eheheh

Thanks in advance!

I renamed to .txt extension to github allow upload individualy.
[graphical-shutdown.ko.txt](https://github.com/rescuezilla/rescuezilla/files/5434964/graphical-shutdown.ko.txt)
[rescuezilla.ko.txt](https://github.com/rescuezilla/rescuezilla/files/5434965/rescuezilla.ko.txt)
[de.ko.txt](https://github.com/rescuezilla/rescuezilla/files/5434966/de.ko.txt)

**Comment by shasheene** [comment]
Hi Vinicios,

Very nice work!

I will include your translation in Rescuezilla v2.1 which will be released in early-November (a few weeks away).

**Comment by vinicioslc** [comment]
Oh thanks, and great work ! the python GUI its much more stable on my tests than of redo rescue.

**Comment by shasheene** [comment]
Thanks! I'm glad you are enjoying using Rescuezilla!

As you know, Rescuezilla v2.0 was completely rewritten from scratch in the Python programming language. I should mention that users have reported [slower backups](https://github.com/rescuezilla/rescuezilla/issues/126) compared to Rescuezilla v1.0.6.1 (1.5GB/minute compared to 4GB/min) and [annoyingly slow scanning](https://github.com/rescuezilla/rescuezilla/issues/126). I will improve things for [Rescuezilla v2.1](https://github.com/rescuezilla/rescuezilla/projects/5).

By the way, I am selecting the Portuguese keyboard layout for your translation. Let me know if this is not sufficient!

**Comment by vinicioslc** [comment]
@shasheene I think it are enough, the recomended layout for majority of Brazil keyboards its ABNT2 instead the Portugal version ABNT only, but i think this translation will be used by our Portugal friends so, i don't care if use ABNT but someone can be furious because they don't know change layout (its a joke ahahah) 
image below compare the both layouts.

![image](https://user-images.githubusercontent.com/10997022/97130336-ecd8fa80-171f-11eb-9434-d1ec0426044e.png)

**Comment by shasheene** [comment]
Thanks for the information. I will choose ABNT2 but add [a desktop icon to switch between keyboard layouts (task #91)](https://github.com/rescuezilla/rescuezilla/issues/91)

**Comment by shasheene** [comment]
Translation now available in [Rescuezilla v2.1](https://github.com/rescuezilla/rescuezilla/releases/latest):

<a href="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pt/grub.png"><img width=300 src="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pt/grub.png"></a> <a href="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pt/welcome.png"><img width=300 src="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pt/welcome.png"></a> <a href="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pt/restore.step2.png"><img width=300 src="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pt/restore.step2.png"></a> <a href="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pt/restore.step4.overwrite.png"><img width=300 src="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pt/restore.step4.overwrite.png"></a> <a href="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pt/restore.step4.not.overwrite.png"><img width=300 src="https://raw.githubusercontent.com/rescuezilla/rescuezilla.github.io/master/media/screenshots/v2.1/pt/restore.step4.not.overwrite.png"></a>
