### ISSUE TITLE
Automatic shutdown or reboot after backup/restore complete

### ISSUE THREAD

**Issue by candrapersada** [rescuezilla/rescuezilla#165]
why is there no automatic Shutdown and Reboot feature after backup and restore is complete like Clonezilla?
![103472028-a99fa580-4dba-11eb-88af-f2405896ca9d](https://user-images.githubusercontent.com/36833664/103472074-642fa800-4dbb-11eb-984d-cbc041ac93aa.png)

**Comment by shasheene** [comment]
Thanks for the feature request. Your request aligns with the [Rescuezilla Project Roadmap](https://github.com/rescuezilla/rescuezilla/wiki/Rescuezilla-Project-Roadmap).

I will add a drop-down menu to the confirmation page to allow the user to select shutdown/reboot/etc. The default action will of course be "do nothing".

I should mention: In the event the operation failed for some reason, some users (such as those with servers) may still want the machine to reboot. However, most users will want to to examine the summary message, so the best design in the event of a failure is to ignore the scheduled action and let the user read the summary message.
