### ISSUE TITLE
Add ability to select compression format (such as zstd/zstandard), compression levels, etc

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#170]
A recurring feature request has been a page to select the compression format and modify the compression levels.

The options provided by Clonezilla's _Expert_ Mode:

![clonezilla expert compression](https://user-images.githubusercontent.com/1414379/101981591-02998380-3cbe-11eb-9dee-94b604f0abc1.png)

And the options provided by Clonezilla's _Beginner_ Mode:

![clonezilla beginner compression](https://user-images.githubusercontent.com/1414379/105126218-30c87980-5b2e-11eb-96ba-ed06d1dc62c1.png)

Rescuezilla v2.0+ can of course restore images created using these settings using Clonezilla, but the ability to use compression formats other than gzip has not been provided until now.

Expert users of Rescuezilla have most often expressed the wish to leverage the advanced zstd/zstandard compression format, a technology developed by Facebook in the mid-2010s which uses the recent advancements in ANS (Asymmetrical Numeric Systems) research to provide significantly better compression ratios while retaining the very fast compression/decompression speeds achieved using multithreaded gzip. This is appropriate and highly desirable so it should definitely be available to Rescuezilla users. It might even make sense to be the _default_ compression format away from "pigz" (which is a fast and multithreaded utility to do gzip compression). Side note: For some reason Clonezilla's default compression continues to be the slow single-threaded gzip, rather than using the much faster multithreaded pigz like Rescuezilla.

But Rescuezilla has an additional requirement: to [instantaneously mount very large (100+GB) Clonezilla backup images (task #153)](https://github.com/rescuezilla/rescuezilla/issues/153) and **[unfortunately zstd suffers the same issues as gzip and xz in that the format is not suitable for random access workloads without either carefully creating backup images with certain "frame" configuration (possible but still a bleeding edge feature, and also unlikely for Clonezila to ever do), or by creating a separate index database which at this stage would requiring a streaming decompression of the _entire_ 100+GB archive on the first image explorer mount](https://github.com/mxmlnkn/ratarmount/issues/40#issuecomment-735421844).** Because of these continuing limitations I am currently unlikely switching the default Rescuezilla compression format to zstd at this moment.

Finally I should mention that adding another page to the Rescuezilla wizard needs to be balanced against keeping Rescuezilla as simple as possible. I intend to achieve this by writing something along the lines of "if you are not sure, please leave these settings unchanged and click Next".

The added complexity to the user-interface is well worth it: the ability to instantaneously mount images by creating them either without compression, or with 16MB block-size and xz compression will be far too important to Rescuezilla users going forward.

**Comment by llvs** [comment]
As of march 2023 (rescuezilla-2.4.2-64bit.jammy) I can't select the zstandard-multithreaded version in the compression drop-down menu. Is multithreading used automatically by default? This would correspond to Clonezilla's -z9p option for parallel zstd.

**Comment by garywill** [comment]
Ehh, why Rescuezilla 2.6.2 not showing zstd option when creating ext4 partition backup ?

Update: Well, it is due to a wrong zh translation. Fix by PR 662
