### ISSUE TITLE
rescuezilla chinese languge

### ISSUE THREAD

**Issue by mzky** [rescuezilla/rescuezilla#191]
hi！
Chinese is my native language，This is the Chinese language package I provided：

[chinese.zip](https://github.com/rescuezilla/rescuezilla/files/6067644/chinese.zip)

**Comment by shasheene** [comment]
Great work, @mzky!

Once the internet outage I'm currently experiencing has been resolved I will create a new unofficial ISO image, then I will test and release it in a comment below.

Side note: As you have likely already read on the previous revision of the "Translations HOWTO" GitHub Wiki page, I have noticed a GitHub user *@XuCpeng had began a [different Chinese (Simplified) translation of Rescuezilla](https://github.com/XuCpeng/rescuezilla/commit/da77611eaaedddc01807058c6de9d3cd3c0ab131)* but it didn't complete it or submit it to me. You or @XuCpeng may be interested in reviewing/comparing both translations side-by-side for the clearest translation possible. It's no big deal if you don't want to.

**Comment by mzky** [comment]
> Great work, @mzky!
> 
> Once the internet outage I'm currently experiencing has been resolved I will create a new unofficial ISO image, then I will test and release it in a comment below.
> 
> Side note: As you have likely already read on the previous revision of the "Translations HOWTO" GitHub Wiki page, I have noticed GitHub user **@XuCpeng had began a [different Chinese (Simplified) translation of Rescuezilla](https://github.com/XuCpeng/rescuezilla/commit/da77611eaaedddc01807058c6de9d3cd3c0ab131)** but didn't complete it or submit it to me. You or @XuCpeng may be interested in reviewing/comparing both translations side-by-side for the clearest translation possible. It's no big deal if you don't want to.

Thank you for everything. I have actually read @XuCpeng's translation. There is no problem with his translation, but after waiting for a few months, the translation still hasn't progressed, which is too slow for me.Due to the complexity and diversity of Chinese,  I try my best to use commonly used written words that are easy for ordinary people to understand, so that my translation can be understood by the vast majority of people.

**Comment by shasheene** [comment]
Perfect! I also previously noticed that you had starred @XuCpeng fork, so I should have known you read that translation. It does look like you have built upon some of his existing translation, and completed the rest of it. I am very glad no work has been duplicated!

My internet outage continues so I will release the ISO image as soon as I can. Stay tuned!

**Comment by XuCpeng** [comment]
Thank you very much for your attention, shasheene. I tried to translate two months ago, but it was temporarily shelved due to work reasons. Nice to see another excellent translator. You can directly receive his work, and I will provide feedback in future use.

**Comment by shasheene** [comment]
The next version is Rescuezilla v2.2 scheduled for May 2021 which is too far away, so I have created a build that's simply Rescuezilla v2.1.3 plus the translation: [rescuezilla-2.1.3-9-g4ade040a-64bit.groovy.iso](https://drive.google.com/u/0/uc?id=1E-twbE3xs66-N3Vexf_hxrRmPh3teJ70&export=download). Feel free to distribute it on forums or anywhere else, as you see fit.

<a href="https://user-images.githubusercontent.com/1414379/110227655-a35caf80-7f4a-11eb-8513-e149df782b34.png" ><img width=350 src="https://user-images.githubusercontent.com/1414379/110227655-a35caf80-7f4a-11eb-8513-e149df782b34.png"></a><a href="https://user-images.githubusercontent.com/1414379/110227661-afe10800-7f4a-11eb-9136-01937760a0a1.png">
<img width=350 src="https://user-images.githubusercontent.com/1414379/110227661-afe10800-7f4a-11eb-9136-01937760a0a1.png"></a> <a href="https://user-images.githubusercontent.com/1414379/110227667-bbccca00-7f4a-11eb-9cab-b81cb94d2901.png"><img width=780 src="https://user-images.githubusercontent.com/1414379/110227667-bbccca00-7f4a-11eb-9cab-b81cb94d2901.png"></a>

For the keyboard I tried to chose the default Chinese keyboard layout and _not_ any of the following variants:
```
  altgr-pinyin    cn: Hanyu Pinyin (altgr)
  tib             cn: Tibetan
  tib_asciinum    cn: Tibetan (with ASCII numerals)
  ug              cn: Uyghur
```
But the keyboard layout I selected not have had any impact. I should mention it's [possible to install and configure ibus, fcitx or scim for Chinese pinyin input](https://wiki.debian.org/InputMethodBuster), but I haven't done this yet.

Checksums:
sha256sum:
bc835e26c39af977bb9cecc6ab2dad838ceafdec76946a1e573e5e1b726d6c13  rescuezilla-2.1.3-9-g4ade040a-64bit.groovy.iso

sha1sum:
82d2969406fa0277600a3d15b1c0e9a8703e2de2  rescuezilla-2.1.3-9-g4ade040a-64bit.groovy.iso

md5sum:
ae3c210334dea87a8b2c2f6e815b53c7  rescuezilla-2.1.3-9-g4ade040a-64bit.groovy.iso

Download: [rescuezilla-2.1.3-9-g4ade040a-64bit.groovy.iso](https://drive.google.com/u/0/uc?id=1E-twbE3xs66-N3Vexf_hxrRmPh3teJ70&export=download)
