### ISSUE TITLE
Ability to restore and explore virtual machine images ("V2P")

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#192]
I've recently come across an _extremely_ powerful tool named [qemu-nbd](https://www.mankier.com/8/qemu-nbd) in the [qemu-utils](https://packages.ubuntu.com/focal/qemu-utils) package. qemu-nbd is a command-line tool that can decode the contents of a wide variety of virtual machine images (such as VDI, VMDK, QCOW2) and present it as a standard Linux block device. It's analogous to the partclone-nbd tool [currently](https://github.com/rescuezilla/rescuezilla/issues/185) used by Rescuezilla Image Explorer. Basically it means you can mount any virtual machine disk format (whether made with VirtualBox, VMWare or QEMU) and access the files inside. I've used VirtualBox for many years and never even knew qemu-nbd existed.

It seems to make a lot of sense to integrate qemu-nbd into Rescuezilla. It would add some very useful features:
1. Ability to mount VM images using Image Explorer and access files
    * I'm unaware of any qemu-nbd graphical frontends. Please let me know if you know of any!
2. Support V2P (Virtual machine to physical machine) operations. **In other words, Rescuezilla's could then "restore" a VM image to a physical machine.**
    * In the past, users have called for [P2V copy (Physical machine to Virtual machine) (task #19)](https://github.com/rescuezilla/rescuezilla/issues/19).
    * I was already intending on adding support [to restore and explore raw "dd" whole disk images and ISO9660 filesystems](https://github.com/rescuezilla/rescuezilla/issues/142) using loop devices. I just checked and qemu-nbd handles both those without issues, so qemu-nbd would integrate into Rescuezilla extremely elegantly.

If you're reading this, please select a reaction emoticon to "vote" for this issue! I suspect this feature will be very popular.

**Comment by shasheene** [comment]
OK I have added the ability to explore virtual machine images, but restoring an image (V2P functionality) can wait until after [cloning (task #42)](https://github.com/rescuezilla/rescuezilla/issues/47) has been implemented.

I have renamed this issue, and will create a new issue to capture the task to implement VM image restore (V2P).

**Comment by candrapersada** [comment]
is it possible to restore from legacy (MBR) to uefi boot (GPT) for virtual machines?

**Comment by shasheene** [comment]
No, not easily.

**Comment by candrapersada** [comment]
will there be support for clone partition or backup partition from host to virtual machine images (such as VDI, VMDK, QCOW2)?

**Comment by shasheene** [comment]
Maybe in the future. Would you use such a feature?

**Comment by candrapersada** [comment]
yes for move linux from host to virtual machine

**Comment by shasheene** [comment]
OK, I'll add the feature for a future version.

**Comment by candrapersada** [comment]
why hasn't this issue been reopened for Ability to backup to virtual machine images?

**Comment by shasheene** [comment]
There is already an open GitHub issue for ["P2V" copy (Physical machine to Virtual machine) (task #19)](https://github.com/rescuezilla/rescuezilla/issues/19).

I am not planning on adding P2V for Rescuezilla v2.3 (scheduled for November 2021), but it's still only a stretch goal for Rescuezilla v2.4 (scheduled for May 2022), because I am expecting the upcoming "undelete" tool (frontend for the TestDisk command-line tool) to be much more widely useful.

I do hope to implement P2V eventually though.
