### ISSUE TITLE
Restoring and exploring images created by FOG Project, Redo Rescue, Foxclone and FSArchiver

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#194]
Despite Clonezilla being the undisputed leader in open-source imaging tools for decades, it would great for Rescuezilla to be able to process images created by the other partclone-based imaging tools: the FOG Project, Redo Rescue and Foxclone.

Whilst all those projects are based on the exact same partclone tool that Clonezilla uses, they choose to handle the metadata, compression and file naming slightly differently, making their images incompatible with each other.

I intend Rescuezilla to be able to restore such images in the future, but until then at least being able to mount and explore such images using Rescuezilla Image Explorer seems like it would be useful.

Related tasks:

* [task #192: Ability to restore and explore virtual machine images ("V2P")](https://github.com/rescuezilla/rescuezilla/issues/192)
* [task #185: Switch from partclone-nbd to partclone-utils](https://github.com/rescuezilla/rescuezilla/issues/185) used by Rescuezilla Image Explorer

**Comment by shasheene** [comment]
OK, so the image format of Redo Rescue and Foxclone turned out to be trivially simple. I am expanding the scope of this task to include adding the ability for Rescuezilla to restore these image too.

I haven't constructed a PXE boot environment for FOG Project though, so I'm still not sure how much effort it will be to add reliable restoring of such images.

Adding 3 new image formats will mean the [automated testing suite for Rescuezilla's long-term maintainability (task #151)](https://github.com/rescuezilla/rescuezilla/issues/151) will be more important than ever.

**Comment by shasheene** [comment]
On top of the 3 image formats described above, I've decided to also add support for Francois Dupoux's [FSArchiver](https://github.com/fdupoux/fsarchiver).

FSArchiver is relatively popular and its standalone ".fsa" archives are very clean compared to Clonezilla's image format. Its command-line tool that happens to be much easier to use for Linux novices than using the partclone command-line directly. There's also a buggy and overly complex frontend named [qt-fsarchiver](https://sourceforge.net/projects/qt-fsarchiver) that has its own ISO live image. Francois Dupoux happened to write "partimage" too. Clonezilla used to use partclone, though not any more since it's being removed from many Linux distributions as it's not maintained.

There's definitely a risk of spreading myself too thin here, but it does seem very useful to handle ".fsa" files. Rescuezilla compatibility would only apply to restoring the images as integrating FSArchiver support into Image Explorer (beta) requires further investigation.

**Comment by mzky** [comment]
At the same time, it is recommended to provide FSArchiver backup, other products do not have this rare function of expanding and shrinking partitions.

**Comment by shasheene** [comment]
I am actually intending to have  a restore operation [automatically resize partitions and filesystems](https://github.com/rescuezilla/rescuezilla/issues/18).

I am intended for this feature to work with **every** image format that Rescuezilla supports, not just FSArchiver. It will mean millions of existing backup images suddenly have a very powerful and useful feature unlocked. The feature should be ready for Rescuezilla v2.3 release (scheduled for November 2021), rather than Recuezilla v2.2 (scheduled for May 2021). 

I'm very hesitant to add FSArchiver as a backup format, though I do see why people would want it. Hopefully once the resize feature is ready it will lower the need to support FSArchiver as a backup option.
