### ISSUE TITLE
Make it easier to translate Rescuezilla by switching to Weblate (or similar application)

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#196]
As of writing Rescuezilla is available in 11 languages: English, French, German, Spanish, Brazilian Portuguese, Polish, Italian, Greek, Japanese, Swedish and Chinese (Simplified).

The [process to translate Rescuezilla](https://github.com/rescuezilla/rescuezilla/wiki/Translations-HOWTO) currently involves downloading several files, opening the files in a text editor, translating each line then submitting the files for me to integrate. This process puts an unfair burden on the original translator who translates all 150 lines. And as Rescuezilla inevitably grows to hundreds of supported languages it will become overwhelming to manually integrate each translation update.

**I am intending on switching to a collaborative website like [hosted Weblate](https://hosted.weblate.org/)**, or one of its alternatives like the [POEditor](https://alternativeto.net/software/po-editor/about/) (which is proprietary, but free for open-source applications).

I am definitely leaning towards a hosted _open-source_ solution like Weblate. Other open-source tools like Pootle and Zanata don't seem to have hosted options. Feel free to post any ideas or suggestions on this below.

**Comment by mzky** [comment]
After using it,I feel delight to find Weblate! I really appreciate this mode of cooperative translatio.

**Comment by shasheene** [comment]
Hi everybody,

Sorry to bother you all. I am tagging you in this post since you all have been interested in translating Rescuezilla.

**Rescuezilla now uses Weblate for translations: https://hosted.weblate.org/projects/rescuezilla/#languages**

Weblate should make it _much_ easier for people to translate Rescuezilla as the project grows to hundreds of supported languages.

Rescuezilla v2.2 will be released in late-May 2021 (less than 2 weeks from now). I've added the highly-requested 'Cloning' mode (for direct device-to-device copying) among many other features. I have also reworded many of the English sentences to be as clear as possible for newbie users, so some of the translations might have become less accurate.

**I would greatly appreciate if you reviewed and translated Rescuezilla into any languages you're familiar with: https://hosted.weblate.org/projects/rescuezilla/#languages**

Thanks again for your support, @pfrouleau, @caralu74, @vinicioslc, @zeit439, @emircankavas, @tkatsageorgis, @AE720, @FX8350, @mzky, @XuCpeng and @AliensInc

\- Shasheen Ediriweera (developer of Rescuezilla)

**Comment by shasheene** [comment]
@Matthaiks, I see you have updated the Polish translation of Rescuezilla. Thank you.

Just to let you know, the translation strings for the new "cloning" feature are now available to be translated:  https://hosted.weblate.org/projects/rescuezilla/rescuezilla/

I'm new to Weblate: I didn't realize I had to manually setup the auto-update. The new lines should be available to translate now! :)

**Comment by shasheene** [comment]
So I've played with Weblate a bit more. It turns out if you're **logged in** to Weblate, there is an "Automatic Suggestions"  tab that becomes available, allowing translators to select the best machine translation:

![automatic translation](https://user-images.githubusercontent.com/1414379/119082140-9bd28000-ba3c-11eb-8a82-82d98a5e08c9.png)

**This tab will definitely save a lot of time, because it means translators only need to review and modify an imperfect machine translation, which is much easier rather than manually translating hundreds of sentences from scratch.**

You have to be logged in to see the tab though.

**Comment by shasheene** [comment]
Sorry for the spam. I just wanted to give anybody reading a final heads up: **Rescuezilla v2.2 is locked in for release on Monday (31 May 2021)**.

You can find the instructions to translate here: https://github.com/rescuezilla/rescuezilla/wiki/Translations-HOWTO I have added context screenshots for almost every sentence, which should make things easier.

[![Translation status](https://hosted.weblate.org/widgets/rescuezilla/-/rescuezilla/multi-auto.svg)](https://hosted.weblate.org/engage/rescuezilla/)

Also, I forgot to tag @AlexTux87 in my earlier comment. My apologies!

**Comment by caralu74** [comment]
I have ended the Spanish translation, so I hope this could be included in the last release and that the translation have few mistakes.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by shasheene** [comment]
Yep, thank you @caralu74 I have just included all the most recent translations, including yours! Your work will be immediately appreciated by the very large Spanish speaking Rescuezilla userbase!

Any and all changes made on Weblate before the 11:59pm on Sunday night will be included in the next release.

Rescuezilla v2.2 will be the first time I am marketing Rescuezilla as a "Clonezilla GUI", so I am expecting it will be an especially popular release, and I think it will reach 100,000 downloads in the first few days (which will be faster than usual).

Thanks again for your translation!

**Comment by shasheene** [comment]
Hi everyone,

**[Rescuezilla  v2.2](https://github.com/rescuezilla/rescuezilla/releases/latest) is now available containing the translation contributions from many users.**

Thanks to everyone who contributed and put up with my @ mentions without unsubscribing to the emails.

Also special shout out to @mzky who translated Chinese (Traditional) **and** much of Chinese (Simplified). Looks like an insane amount of work!
