### ISSUE TITLE
rescuezilla Chinese (Simplified) language update

### ISSUE THREAD

**Issue by mzky** [rescuezilla/rescuezilla#197]
Hi! After verification and proofreading by colleagues, the duplicate content and some loose descriptions were corrected.

[chinese_simplified.zip](https://github.com/rescuezilla/rescuezilla/files/6140300/chinese_simplified.zip)

**Comment by shasheene** [comment]
Thanks for the updates!

Your translation looks good time. The only issue I see is the earlier translation of "Load USB into RAM" was "将USB加载到RAM上" but now it's "USB设备启动". As you may know the description of that menu item is "loads Rescuezilla into memory allowing the boot media to be ejected after bootup" (which you've just translated as 将Rescuezilla加载到内存中启动).

**Given this, is the first translation still more accurate? Or is there another way to phrase it?**

By the way, the files you've modified are actually out-of-date. I was able to integrate the work you've just sent me without issues though. For reference, here are the most recent accepted/approved translation files for Chinese (zh language code):

    * [src/livecd/image/boot/grub/locale/zh.ko](https://raw.githubusercontent.com/rescuezilla/rescuezilla/master/src/livecd/image/boot/grub/locale/zh.ko)
    * [src/apps/rescuezilla/rescuezilla/usr/share/locale/zh/LC_MESSAGES/rescuezilla.ko](https://raw.githubusercontent.com/rescuezilla/rescuezilla/master/src/apps/rescuezilla/rescuezilla/usr/share/locale/zh/LC_MESSAGES/rescuezilla.ko)
    * [src/apps/graphical-shutdown/graphical-shutdown/usr/share/locale/zh/LC_MESSAGES/graphical-shutdown.ko](https://raw.githubusercontent.com/rescuezilla/rescuezilla/master/src/apps/graphical-shutdown/graphical-shutdown/usr/share/locale/zh/LC_MESSAGES/graphical-shutdown.ko)

As you may have read [I will be switching to Weblate or similar collaborative online tool for future Rescuezilla translations](https://github.com/rescuezilla/rescuezilla/issues/196). This will mean making translations and updating them will become much easier with very easy collaboration!

**Comment by mzky** [comment]
To understand this, I took an example from the Google result:

“ USB设备启动”is obviously more applicable：
![image](https://user-images.githubusercontent.com/13345233/111257261-c3305980-8655-11eb-9ac4-1b100070e990.png)

“将USB加载到RAM上” is a correct but uncommon description：
![image](https://user-images.githubusercontent.com/13345233/111257368-f672e880-8655-11eb-910a-c14dffa07b74.png)

As you know, Chinese is not as strict as German,Don't worry about it, this is a common situation.
When using WebRate, I will continue to translate the new changes！

**Comment by shasheene** [comment]
OK, thanks for the confirmation. I don't speak Chinese so I was just going by the meaning that Google translate was generating.

Because the May 2021 Rescuezilla v2.2 release date is still too far away, later today I will create a new unofficial ISO image that's simply v2.1.3 with the most recent translation updates!

**Comment by shasheene** [comment]
OK, the next version is Rescuezilla v2.2 scheduled for May 2021 which is too far away, so I have created a build that's simply Rescuezilla v2.1.3 plus the translation updates: [rescuezilla-2.1.3-11-gad892bdd-64bit.groovy.iso](https://drive.google.com/u/0/uc?id=1KMwn0OnxqX-6pqnv5Mf0E9YT569xZ9p9&export=download). Feel free to distribute it on forums or anywhere else, as you see fit.

<a href="https://user-images.githubusercontent.com/1414379/111443854-b6952980-8759-11eb-982f-9d6e88b22465.png"><img width=780 src="https://user-images.githubusercontent.com/1414379/111443854-b6952980-8759-11eb-982f-9d6e88b22465.png"></a>

Checksums:
sha256sum:
6347d98174452d634af42d0cebec7f96222d7d3e6deff9f69a972c93a8d9b11c  rescuezilla-2.1.3-11-gad892bdd-64bit.groovy.iso

sha1sum:
d739707c5d95e02d82b235cbd059e3bd6a8f09b8  rescuezilla-2.1.3-11-gad892bdd-64bit.groovy.iso

md5sum:
9bcae3d3eaff6f062ba07067afa25af4  rescuezilla-2.1.3-11-gad892bdd-64bit.groovy.iso

Download: [rescuezilla-2.1.3-11-gad892bdd-64bit.groovy.iso](https://drive.google.com/u/0/uc?id=1KMwn0OnxqX-6pqnv5Mf0E9YT569xZ9p9&export=download)
