### ISSUE TITLE
Navigating backup images and restoring individual files

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#20]
Navigating backups to be able to restore individual files has been requested many times in the past.

Partclone supports --restore_raw_file flag to create a loop device using the sparse image, which can then be mounted and navigated.

The core functionality is present, so the task to turn it into an easy-to-use graphical utility that's logically integrated into Rescuezilla. This feature is heavily dependent on sufficient support on [Patreon](https://www.patreon.com/rescuezilla).

**Comment by FluorescentGreen5** [comment]
A simple file browsing program that runs on a normal OS (instead of having to shutdown the OS and boot into the live Rescuezilla OS) would also be nice, even if it's just a command-line program that lets you get directory listings within the backup and extract individual files (or even entire folders in the future).

If going the command-line route, the syntax could be something like this:

- `rzbrowse <.backup file> -l` lists the partitions inside the backup.
- `rzbrowse <.backup file> -l <partition identifier>` shows a directory listing of the root of that partition. You could also specify a path like `"<parition identifier>/Users/John Smith/Documents"` to view the contents of those directories.
- `rzbrowse <.backup file> -e "<partition identifier>/path to/backed up/file" "C:/path to/extract to"` extracts files inside the backup to an actual folder you specify.

**Comment by shasheene** [comment]
Sneak peek of Rescuezilla's "image explorer" wizard:

<a href="https://user-images.githubusercontent.com/1414379/99037906-94857200-25d4-11eb-81bc-cdbf2fad9b62.png"><img width=245 src="https://user-images.githubusercontent.com/1414379/99037906-94857200-25d4-11eb-81bc-cdbf2fad9b62.png"></a> <a href="https://user-images.githubusercontent.com/1414379/99037910-95b69f00-25d4-11eb-8f63-876efe8d759b.png"><img width=245 src="https://user-images.githubusercontent.com/1414379/99037910-95b69f00-25d4-11eb-8f63-876efe8d759b.png"></a> <a href="https://user-images.githubusercontent.com/1414379/99037912-964f3580-25d4-11eb-90cb-8393c91fa168.png"><img width=245 src="https://user-images.githubusercontent.com/1414379/99037912-964f3580-25d4-11eb-90cb-8393c91fa168.png"></a>

Currently based on partclone's `--restore_raw_file` flag (which the manual says that this feature creates a "special raw file for loop device"), which makes the feature not very useful right now because it's slow speed and _extremely_ large RAM requirements, but I will integrate a lightweight partclone imaging mounting solution soon.

**Comment by shasheene** [comment]
Sneak peek of Rescuezilla's "image explorer" wizard:

<a href="https://user-images.githubusercontent.com/1414379/99037906-94857200-25d4-11eb-81bc-cdbf2fad9b62.png"><img width=780 src="https://user-images.githubusercontent.com/1414379/99037906-94857200-25d4-11eb-81bc-cdbf2fad9b62.png"></a> <a href="https://user-images.githubusercontent.com/1414379/99037910-95b69f00-25d4-11eb-8f63-876efe8d759b.png"><img width=780 src="https://user-images.githubusercontent.com/1414379/99037910-95b69f00-25d4-11eb-8f63-876efe8d759b.png"></a> <a href="https://user-images.githubusercontent.com/1414379/99037912-964f3580-25d4-11eb-90cb-8393c91fa168.png"><img width=780 src="https://user-images.githubusercontent.com/1414379/99037912-964f3580-25d4-11eb-90cb-8393c91fa168.png"></a>

Currently based on partclone's `--restore_raw_file` flag (which the manual says that this feature creates a "special raw file for loop device"), which makes the feature not very useful right now because it's slow speed and _extremely_ large RAM requirements, but I will integrate a lightweight partclone imaging mounting solution soon.

**Comment by FluorescentGreen5** [comment]
I like where this is going. Dumb question, but will the image be opened as read-only?

**Comment by shasheene** [comment]
Not a dumb question, but yes the image will be opened as read-only.

**Comment by shasheene** [comment]
^Anybody reading this please ignore that status update moving the project into 'Done' -- I had brought my computer out of screensaver and accidentally dragged the card into a new column.

The integration of image explorer functionality is proceeding well. Few more things to do before I can park the work and move on to other Rescuezilla v2.1 tasks.

**Comment by shasheene** [comment]
Feature added in [Rescuezilla v2.1](https://github.com/rescuezilla/rescuezilla/releases/latest)

**Comment by candrapersada** [comment]
> Not a dumb question, but yes the image will be opened as read-only.

whether the file can be copied and transferred? and and whether it can read NTFS file?

**Comment by shasheene** [comment]
@candrapersada,

Image Explorer is able to mount and explore backup images created from variety of filesystems. Mounting NTFS backup images is no problem:

<a href="https://rescuezilla.com/media/screenshots/9.png"><img width=780 src="https://rescuezilla.com/media/screenshots/9.png"></a> <a href="https://rescuezilla.com/media/screenshots/10.png"><img width=780 src="https://rescuezilla.com/media/screenshots/10.png"></a>

**For Rescuezilla v2.1 the feature is still in beta.** One reason why the feature is still in beta is because it's not easy to copy your files to a new destination drive. Currently the easiest way is to copy the files to the desktop first then close and unmount Rescuezilla then copy the files. This is fine for small files, but not suitable for large files.

Right now the best way (for advanced users) is to to use the command line and mount your destination drive. Then use the command line to copy files. This is difficult for most Rescuezilla users though.

From your earlier post (https://github.com/rescuezilla/rescuezilla/issues/145) this feature is actually very suitable for you, @candrapersada, because you have lots of relatively small partitions (~30GB) which makes the mounting step much faster than for people with larger partitions. Even so, you might find Image Explorer still too slow to be usable. I hope to make all operations work instantaneously in the future by changing the compression settings.

Let me know how you go

**Comment by dJani97** [comment]
Can I run this utility on a desktop Linux without booting into Rescuezilla?
