### ISSUE TITLE
[Question] Help to Partition Strategy with Rescuezilla? 🚀

### ISSUE THREAD

**Issue by martinandersen3d** [rescuezilla/rescuezilla#231]
### "I have a dream:"

- I would like to create a partition where Rescuezilla, run as its own operation system. 
- My motivation is that i don't have to fiddle with usb-stick all the time - _**And then take backup more often.**_
- From grub i would like to boot into this partition
- When booted into the Rescuezilla-partition, I can take backup of the Ubuntu/Main-OS, to a "Data & Backup" partition.

How can I make this possible? Can I somehow extract the Rescuezilla ISO to a partition, and it will magically work? 😁🤗🤭🥳

Shoot! Everything can help 🥰😇

![image](https://user-images.githubusercontent.com/19984581/121968965-99c9bb80-cd73-11eb-9c3e-99daf2600c23.png)

**Comment by shasheene** [comment]
Hi,

I see you have created a [Sourceforge forum post on this same question](https://sourceforge.net/p/rescuezilla/discussion/support/thread/69cae436be), let's continue there.
