### ISSUE TITLE
Duplicate image name warning soft locks Rescuezilla

### ISSUE THREAD

**Issue by AE720** [rescuezilla/rescuezilla#238]
If I have an image already made and I name another one the same, it will stop me with a non-user friendly error message warning me the name already exists, followed by being stuck in that window until I close and reopen it. I suggest just a message saying an image with that name exists and going back to the screen before it)

**Comment by shasheene** [comment]
Good find. The default backup name contains a timestamp, but I can understand people would delete the default name and put something else in.

As you may know, Rescuezilla has a 6-monthly release cycle, with Rescuezilla v2.3 scheduled for November 2021. I haven't received many bug reports, so unlike previous releases **at this stage** it looks like there **won't** be a "Rescuezilla v2.2.1" sooner than that.

Feel free to create GitHub issues for all bugs you come across (even if they're minor), and/or post detailed feedback on the Sourceforge forum. I'll integrate changes/feedback for Rescuezilla v2.3.
