### ISSUE TITLE
Hebrew translation

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#244]
Hi @yarons and @mkolesnik,

I see you have [translated Rescuezilla using Weblate](https://github.com/rescuezilla/rescuezilla/wiki/Translations-HOWTO). Great work!

The next version (Rescuezilla v2.3) is scheduled for November 2021. This is unreasonably far away, so I have created a build that's simply Rescuezilla v2.2 plus the recent Weblate translations, including Hebrew: **[rescuezilla-2.2-28-g14e761ed-64bit.hirsute.iso](https://drive.google.com/uc?id=1_0kb4c2rntpGdy8Z30peiCwC5vGGW_6J&export=download)**. Feel free to distribute it on forums or anywhere else, as you see fit.

(Note: There has been reports of the Hirsute version has trouble reaching the desktop on some systems. If so try choosing the 'Graphical Fallback Mode' item from the boot menu (after selecting a language). Rescuezilla v2.3 will have a more recent Linux kernel which is expected to resolve this issue.)

<a href="https://user-images.githubusercontent.com/1414379/125094287-48aeac80-e112-11eb-9291-9eadf5486721.png"><img width=350 src="https://user-images.githubusercontent.com/1414379/125094287-48aeac80-e112-11eb-9291-9eadf5486721.png"></a> <a href="https://user-images.githubusercontent.com/1414379/125094469-6f6ce300-e112-11eb-8d24-5a09147920e9.png"><img width=350 src="https://user-images.githubusercontent.com/1414379/125094469-6f6ce300-e112-11eb-8d24-5a09147920e9.png"></a> <a href="https://user-images.githubusercontent.com/1414379/125094398-611ec700-e112-11eb-9c49-1f56821822e1.png"><img width=780 src="https://user-images.githubusercontent.com/1414379/125094398-611ec700-e112-11eb-9c49-1f56821822e1.png"></a>

For the keyboard I have chosen the standard Hebrew keyboard layout and _not_ any of the following variants:
```
  lyx             il: Hebrew (lyx)
  phonetic        il: Hebrew (phonetic)
  biblical        il: Hebrew (Biblical, Tiro)
```

Checksums:
```
sha256sum
c83f014405ebf40b3d5d120848bcebc76655b9e5ac506eab283e46f957f4e5e1  rescuezilla-2.2-28-g14e761ed-64bit.hirsute.iso
sha1sum
31f725645d8f45d2ced17c40da6ae3e5003ff11f  rescuezilla-2.2-28-g14e761ed-64bit.hirsute.iso
md5sum
abbd7f563203b22ef9248551130eeafd  rescuezilla-2.2-28-g14e761ed-64bit.hirsute.iso
```
Download: [rescuezilla-2.2-28-g14e761ed-64bit.hirsute.iso](https://drive.google.com/uc?id=1_0kb4c2rntpGdy8Z30peiCwC5vGGW_6J&export=download)

**Comment by shasheene** [comment]
By the way, this is the first right-to-left language available in Rescuezilla. Everything appears to work correctly without any extra work on my part. But please let me know if you run into any issues.

**Comment by yarons** [comment]
You're right about the Hebrew keyboard.

The rest of the problems are probably Xfce related so we'll need to fix some things there as well.

I'll check this version and take some screenshots if I'll find weird stuff in there.

Thank you very much!

**Comment by shasheene** [comment]
> I'll check this version and take some screenshots if I'll find weird stuff in there.

Sounds good!

Just for your own information, the Rescuezilla desktop environment is _not_ Xfce but LXDE. Most desktop components are from LXDE but I have chosen certain standalone applications from the Xfce project (like the terminal). It's not clear the future of the LXDE project itself, because its developers appear to have moved to developing "LXQt". I might switch Rescuezilla to LXQt in the future after I have evaluated it.

I am aware of issues like the 'Shutdown' start menu entry not having a translation selected across all languages (but the actual "graphical-shutdown" application itself being correctly translated).

Finally, the Rescuezilla application itself was developed using GTK framework. So if there is any problems with right-to-left language support within the Rescuezilla application itself and other similar applications then it's the GTK developers who may need to be contacted with bug reports.

**All that said, feel free to create GitHub issues (or Sourceforge forum posts) about any bugs/issues/suggestions for Rescuezilla (whether translation related or otherwise), and I'll try and integrate the feedback into future versions.**

**Comment by yarons** [comment]
I used to translate LXDE and now I'm translating LXQt so it should be fine.

GTK usually supports RTL, the only problems we're usually facing are arrows.

**Comment by shasheene** [comment]
> the only problems we're usually facing are arrows.

Oh I see: by arrows you mean Rescuezilla's text arrows like "---->".

Yep, that's part of the Rescuezilla code so I can easily improve that so it's automatically displayed as facing the opposite direction for RTL languages. Thanks for the report!

**Comment by yarons** [comment]
They should be flipped accordingly.

Usually the problem with GTK is forward/backwards, the original will probably look like this < >, the RTL version will make these fight against each other >< (pointing one another).

I haven't seen such in your UI but it happened in the past for sure and the fix is pretty funny :)

**Comment by shasheene** [comment]
Yep sounds good: I'll switch to using GTK's arrows (or where relevant, the unicode characters: ← and →), and I'll be especially careful to use the actual bidirectional arrows characters (such as ↔) rather than placing two characters (←→) so avoid an incorrect get inverted.

**Comment by yarons** [comment]
That's great althouh I'm pretty sure Unicode can handle that automatically :)

**Comment by shasheene** [comment]
@yarons and @mkolesnik,

Rescuezilla v2.3 is finally officially released, so your great work can finally be used widely!
