### ISSUE TITLE
translation into Russian

### ISSUE THREAD

**Issue by ttt113326** [rescuezilla/rescuezilla#270]
I drew attention to your program as it says "translation into Russian". It turned out that the translation is very incomplete. Especially in important, key points in the dialogue, where the user is required to understand in order to make decisions. In fact, only 2 buttons are translated: "next" and "back" and in the header - what status you are in now: Backup or Restore. The dialogues themselves have not been translated into Russian in any way.

![shag1](https://user-images.githubusercontent.com/1414379/136637994-59f6a8b3-d79c-4646-aec1-b7b0d0c4a20f.png)

If the problem lies in the unpredictable display of the encoding, then translate Russian words into Latin transcription.
For example:
** Select Drive To Backup **
Replaced by:
** Viberite Disk Dlya Rezervnogo Kopirovaniya **
(Select Disk To Back Up)

**Comment by shasheene** [comment]
You are right: in the Rescuezilla v2.2 release notes I should have been more clear about the "in-progress" status of the translation (like I have in the README file). At the time of Rescuezilla v2.2 release, somebody had started a Russian translation but never came back to finish it. I decided to release that partial translation and [encourage the my Russian users (on the OpenNet.RU forum)](https://www.opennet.ru/opennews/art.shtml?num=55278) to help [complete the translation on Weblate](https://github.com/rescuezilla/rescuezilla/wiki/Translations-HOWTO).

Well, that strategy worked pretty well: **[Currently the Russian translation on Weblate is a respectable 78% complete](https://hosted.weblate.org/projects/rescuezilla/rescuezilla/ru/)**. Here is a screenshot of their great work so far:

![RU](https://user-images.githubusercontent.com/1414379/136638042-6f0dd056-1fae-41ae-99ef-86bc7c459522.png)

This updated and improved translation will be available in Rescuezilla v2.3 (scheduled for release next month: November 2021).

If you're interested in contributing to the Rescuezilla translations, [you can do so from Weblate](https://github.com/rescuezilla/rescuezilla/wiki/Translations-HOWTO). I highly recommend creating an account on Weblate so that you can "save" translations rather than merely "suggest" them!

**Comment by shasheene** [comment]
@ttt113326 I have seen you have been generously submitting the remaining Rescuezilla translations for the Russian language up to 98% complete, and that you have recently started 'watching' the project on GitHub. I presume you are eagerly awaiting the next version where you can finally your great work!

I have just "accepted" the remaining 2%: 8 lines where (as you may know) translations were simply "suggested" by an anonymous user submitting them 4 months ago in a drive-by fashion (I hadn't noticed those handful of "suggested" translations earlier).

I'm writing this comment to say that the next version (Rescuezilla v2.3) is scheduled for a month away, which is unreasonably far away given the effort you have put in over the last few days, **so in about 6 hours I will be doing what I have always done for other translations submitted "between" the large official releases: I will make an "unofficial" build** that's Rescuezilla v2.2 plus your translation work, and I'll post this link here. Here are some recent examples of me doing (the GitHub has many more):

https://github.com/rescuezilla/rescuezilla/issues/244
https://github.com/rescuezilla/rescuezilla/issues/244
https://github.com/rescuezilla/rescuezilla/issues/248

This will allow us to find any errors before the official release, and allow you to enjoy your work much sooner!

**Comment by shasheene** [comment]
Even though you're not looking for an immediate Russian-language version, other people might be. 

I have created a build that's simply Rescuezilla v2.2 plus the recent Weblate translations, including Russian: **[rescuezilla-2.2-91-gb30b6ea6-64bit.hirsute.iso](https://drive.google.com/u/0/uc?id=1FuzNlnlumJXzLmMbWGDb0mC27hYBzkuv&export=download)**. If you're reading this, feel free to distribute it on forums or anywhere else, as you see fit.

The only issue I've found is very minor. The translation of "Graphical fallback mode" is one character too long (second line of the screenshot below). If this is a problem, it could be worth modifying the wording of the translation to be 1 characters shorter (but it's up to you): https://hosted.weblate.org/translate/rescuezilla/grub-boot/ru/?q=state%3A%3E%3Dtranslated&offset=3

(Note: There has been reports of the Hirsute version has trouble reaching the desktop on some systems. If so try choosing the 'Graphical Fallback Mode' item from the boot menu (after selecting a language). Rescuezilla v2.3 will have a more recent Linux kernel which is expected to resolve this issue.)

<a href="https://user-images.githubusercontent.com/1414379/137247958-db95436e-86a7-4541-9345-568eac38354c.png"><img width=350 src="https://user-images.githubusercontent.com/1414379/137247958-db95436e-86a7-4541-9345-568eac38354c.png"></a> <a href="https://user-images.githubusercontent.com/1414379/137247977-fe2db6ef-321a-4b8e-992a-3c879c2d6732.png"><img width=350 src="https://user-images.githubusercontent.com/1414379/137247977-fe2db6ef-321a-4b8e-992a-3c879c2d6732.png"></a> <a href="https://user-images.githubusercontent.com/1414379/137247968-857304c5-72d7-4c54-90fc-2c2723577b13.png"><img width=780 src="https://user-images.githubusercontent.com/1414379/137247968-857304c5-72d7-4c54-90fc-2c2723577b13.png"></a>

For the keyboard I have chosen the standard Russian keyboard layout and _not_ any of the following variants:
```
  rus             us: Russian (US, phonetic)
  rus             cz: Russian (Czech, phonetic)
  ru              ge: Russian (Georgia)
  ru              de: Russian (Germany, phonetic)
  ruskaz          kz: Russian (Kazakhstan, with Kazakh)
  kazrus          kz: Kazakh (with Russian)
  ru_phonetic_dvorak pl: Russian (Poland, phonetic Dvorak)
  phonetic        ru: Russian (phonetic)
  phonetic_winkeys ru: Russian (phonetic, with Win keys)
  phonetic_yazherty ru: Russian (phonetic yazherty)
  typewriter      ru: Russian (typewriter)
  legacy          ru: Russian (legacy)
  typewriter-legacy ru: Russian (typewriter, legacy)
  tt              ru: Tatar
  os_legacy       ru: Ossetian (legacy)
  os_winkeys      ru: Ossetian (Win keys)
  cv              ru: Chuvash
  cv_latin        ru: Chuvash (Latin)
  udm             ru: Udmurt
  kom             ru: Komi
  sah             ru: Yakut
  xal             ru: Kalmyk
  dos             ru: Russian (DOS)
  mac             ru: Russian (Macintosh)
  srp             ru: Serbian (Russia)
  bak             ru: Bashkirian
  chm             ru: Mari
  phonetic_azerty ru: Russian (phonetic, AZERTY)
  phonetic_dvorak ru: Russian (phonetic, Dvorak)
  phonetic_fr     ru: Russian (phonetic, French)
  rus             se: Russian (Sweden, phonetic)
  rus_nodeadkeys  se: Russian (Sweden, phonetic, no dead keys)
  rstu_ru         ua: Russian (Ukraine, standard RSTU)
```

Checksums:
```
sha256sum:
2a048922a07ea6fa4864fd6116895eacccea8a109d83a304fd22f53515b62130  rescuezilla-2.2-91-gb30b6ea6-64bit.hirsute.iso

sha1sum:
d68e5b2de5dc67ee598a3f3b961adfda3c1de378  rescuezilla-2.2-91-gb30b6ea6-64bit.hirsute.iso

md5sum:
65be09960cdb04ffed96124004bf05f8  rescuezilla-2.2-91-gb30b6ea6-64bit.hirsute.iso
```
Download: [rescuezilla-2.2-91-gb30b6ea6-64bit.hirsute.iso](https://drive.google.com/u/0/uc?id=1FuzNlnlumJXzLmMbWGDb0mC27hYBzkuv&export=download)
