### ISSUE TITLE
Invisible fonts

### ISSUE THREAD

**Issue by Auronius** [rescuezilla/rescuezilla#274]
Good day!
When I run backup wizard, I have invisible fonts in file names.
The same thing is in restore wizard. I can not see the file names.
![InvisibleFonts1](https://user-images.githubusercontent.com/13540006/137533688-29d32ff7-1ce1-44c2-ada4-b7f73ca7d93a.jpg)
![InvisibleFonts2](https://user-images.githubusercontent.com/13540006/137533700-b3c22a67-710f-4bf7-8d69-f598d7278411.jpg)
![InvisibleFonts3](https://user-images.githubusercontent.com/13540006/137533711-0eddb1af-e0f6-411d-86ae-1a1234799e4b.jpg)

**Comment by shasheene** [comment]
Woah, that's crazy!

It's normal for the "existing image table" shown in your first two screenshots to be grayed out (as that table is not configured to be selectable at that stage in the Rescuezilla wizard).

But the file selection window should definitely have a proper black font color.

It could be a themeing issue. You're running this from a Rescuezilla v2.2 live environment, right? Are you using the Focal or Hirsute version?

It's definitely a weird bug. Does it happen every time you restart?

**Comment by Auronius** [comment]
I am running Rescuezilla v.2.2 x64 Focal. Live environment.
Yes, that is happening every boot.

**Comment by shasheene** [comment]
@Auronius I don't recall if I asked you this. Can this issue be reproduced on Rescuezilla v2.2 x64 _Hirsute_? Note: You may need to select 'Graphical Fallback Mode' to see the desktop on that version.

Rescuezilla v2.3 will have a version based on Ubuntu 21.10 (Impish), which is even more recent than Ubuntu 21.04 (Hirsute) let alone the Ubuntu 20.04 (Focal) release you have been using.

**Comment by shasheene** [comment]
@Auronius can this issue be reproduced on Rescuezilla v2.3 "Impish".

Please try selecting "'Graphical Fallback Mode" after selecting "English" from the boot menu.

**Comment by shasheene** [comment]
The fonts listed in the image list during _backup_ and the backup percentage are meant to be grayed out, with it being OK if it's kind of unreadable. It's certainly unfortunate it's too unreadable though, and maybe I should try and find a way to increasing the contrast / changing the font color.

But please try the following workaround to change the theme to see if there are any improvements:

1. Close all applications
2. Open Terminal from desktop icon
3. 4. Run `lxappearance`
4. Change theme to "Breeze-Dark" and click 'Apply':
  * <a href="https://user-images.githubusercontent.com/1414379/137627978-1a563a0e-1bef-4700-a84c-97e73f4206e2.png"><img width=250 src="https://user-images.githubusercontent.com/1414379/137627978-1a563a0e-1bef-4700-a84c-97e73f4206e2.png"></a>
5. Launch Rescuezilla from desktop icon:
  * <a href="https://user-images.githubusercontent.com/1414379/137627982-e3af1491-60a4-4066-8e60-d4708fed12ea.png"><img width=500 src="https://user-images.githubusercontent.com/1414379/137627982-e3af1491-60a4-4066-8e60-d4708fed12ea.png"></a>

Does that have improved readability?

**Comment by shasheene** [comment]
`lxappearance` now available from [Rescuezilla v2.4.2](https://github.com/rescuezilla/rescuezilla/releases/latest)

**Comment by Auronius** [comment]
This bug still has not been fixed! In Rescuezilla 2.4.2 Focal, I still have invisible fonts. https://i.postimg.cc/fWdtbwhC/Invisible-Font.jpg
Why have you closed it?
Also, lxappearance does not working properly in Rescuezilla 2.4.2 Focal.
