### ISSUE TITLE
Rescuezilla dark theme

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#275]
An anonymous user recently [wrote](https://sourceforge.net/p/rescuezilla/discussion/support/thread/3fa0bdfdef/?limit=25#18d2):

> A dark theme would be a great addition

So quick background: Rescuezilla is an application built using the popular GTK graphical toolkit, which has full support for theming. After [user feedback](https://github.com/rescuezilla/rescuezilla/issues/52), Rescuezilla v2.0 switched to the attractive "Breeze theme" (used by the popular KDE desktop environment).

The "Breeze theme" available in the Rescuezilla live environment comes with a dark theme, but as of Rescuezilla v2.2 there is no easy toggle to enable it. Currently the user has to run the following commands:

1. Close all applications
2. Open Terminal from desktop icon
3. Run `apt-get update && apt-get install lxappearance`
4. Run `lxappearance`
5. Change theme to "Breeze-Dark" and click 'Apply':
  * <a href="https://user-images.githubusercontent.com/1414379/137627978-1a563a0e-1bef-4700-a84c-97e73f4206e2.png"><img width=250 src="https://user-images.githubusercontent.com/1414379/137627978-1a563a0e-1bef-4700-a84c-97e73f4206e2.png"></a>
6. Launch Rescuezilla from desktop icon:
  * <a href="https://user-images.githubusercontent.com/1414379/137627982-e3af1491-60a4-4066-8e60-d4708fed12ea.png"><img width=500 src="https://user-images.githubusercontent.com/1414379/137627982-e3af1491-60a4-4066-8e60-d4708fed12ea.png"></a>

**Just pre-installing `lxappearance` and providing a desktop icon seems to be a reasonable solution.** This doesn't provide dark themes for the file manager, the Firefox web browser or the mousepad text editor. I'm not fully certain why at this stage. But at least it's something.

Of course Rescuezilla does not yet have a [persistent partition between boots (task #8)](https://github.com/rescuezilla/rescuezilla/issues/8), so it would mean users of the live USB environment would have to repeat the steps each reboot. But it's only a few easy clicks.

Installing `lxappearance` definitely seems worth the 500 kilobyte install size. I'm not yet convinced adding a desktop icon is worth the clutter though.

**Feel free to post your opinions as a comment below (or select a reaction emoticon).**

**Comment by compicat** [comment]
Just a noob question. Is it possible approach "persistence thing" via ventoy? It can work like Linux Mint via Ventoy?

https://www.ventoy.net/en/plugin_persistence.html

**Comment by compicat** [comment]
> Not noob question, but answered here: [#8 (comment)](https://github.com/rescuezilla/rescuezilla/issues/8#issuecomment-784636561)

For the ones who have been looking for temporary solution for persistent thing with ventoy, i confirm that ubuntu casper-rw persistent.dat file is working flawless with rescuzilla focal version. It is helpful for keeping dark theme and some small enhancements like preventing "tearing screen" etc. persistent.

**Comment by shasheene** [comment]
Great to hear! I will document that approach for my upcoming Rescuezilla v2.3 documentation on persistence approach. To re-iterate Ventoy's solution is certainly not recommended for holding multi-terabyte images, but for minor configuration changes it sounds perfect!

**Comment by compicat** [comment]
of course, you are right about your concerns which are about backups. But, this is my honest opinion, you should really think about suggesting ventoy-persistence thing. Plenty of stuff including timezone, ibus (of course for non-us users), theme etc. only will be solved via this way as i understand in short term. Also, even if you solve persistence thing for rescuezilla, it will be only eligible for one dedicated usb for rescuezilla. This approach is not that suitable for the users who use ventoy and can even use different boot conf files via ventoy for several ISOs. Thanks for good work again.

**Comment by shasheene** [comment]
Of course! I am intending on documenting and thoroughly testing the Ventoy persistence approach and have it as an officially supported option! :)

The next two weeks or so I am focusing on Rescuezilla v2.3 full-time :)
