### ISSUE TITLE
Backing up same partition twice fails

### ISSUE THREAD

**Issue by mrx23dot** [rescuezilla/rescuezilla#286]
Backing up my Windows7 partition worked for first time.

But gave this error for the 2nd time (without reboots between):
![IMG_20211116_234411_1](https://user-images.githubusercontent.com/4163396/142200392-ef69b202-c515-4517-8608-47540070310f.jpg)

I guess there is some mounting issue going on.
Used 1.0.6.1-32bit (latest 32bit version)

**Comment by mrx23dot** [comment]
If it's fixed in v2 then please release a 32bit version of that, 32bit can backup 32bit and 64bit systems too, 64bit cant.

**Comment by shasheene** [comment]
Yes, this mount thing is not an issue on modern versions of Rescuezilla.

**Really the main issue you're concerned with is: [Bring back 32-bit (i386) version to support computers from before ~2006 (task #232)](https://github.com/rescuezilla/rescuezilla/issues/232).**
