### ISSUE TITLE
Add ability to create images with more compression options (including bzip2 and others)

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#290]
A [user](https://sourceforge.net/p/rescuezilla/discussion/support/thread/866ed6b9c5/?limit=25#da7d) has called for Rescuezilla's user-interface to be able to _create_ images using bzip2 compression and other compression formats that Clonezilla supports.

Current Rescuezilla can only restore images created with advanced Clonezilla compression options, but the user-interface is limited to gzip, zstd and uncompressed.

The user also suggests "z2p" and "z5p", where the number is [Clonezilla's terminology for the different compression implementations (eg, 1 for gzip, 2 for bzip2), and the optional 'p' refers to the parallel variants](https://drbl.org/faq/fine-print.php?path=./2_System/78_clonezilla_compression_option.faq#78_clonezilla_compression_option.faq)

It's a trivial task, but potentially complicates the user-interface so has to be examined.

**Comment by Augusto7743** [comment]
"It's a trivial task, but potentially complicates the user-interface so has to be examined."
A button to configure what compressor will be used help very much.
Is good use the bzip2 maximum compression how is possible in Clonezilla.

**Comment by shasheene** [comment]
@Augusto7743, can you confirm you're using the latest version of Rescuezilla? Because since v2.2 Rescuezilla already has a page to configure which compression gets used. This page is only present during a "Backup", not during a "Clone". There are 3 options: zstd, gzip and uncompressed. The first two provide a slider to determine compression level.

Can you please specify _exactly_ what you would like to see and I'll try to figure out if there's a way to accomodate it.

Currently copying Clonezilla's "p" suffix (eg, "z2p") using a checkbox doesn't seem like a good solution. I'd rather simply offer only parallel bzip ("pbzip2") if a "bzip" item is selected. just like I already select parallel gzip ("pigz") when the "gzip" command is selected.

**Comment by Augusto7743** [comment]
rescuezilla-2.2-64bit.hirsute.iso

Clonezilla list bzip2 being maximum compression

**Comment by Augusto7743** [comment]
Seeing in Rescuezilla 2.3 changelog not have details about added bzip2 and clicking in https://github.com/rescuezilla/rescuezilla/projects/9 not details about bzip2.
Bzip2 support was added in Rescuezilla 2.3 ?

**Comment by shasheene** [comment]
Sorry, no bzip2 didn't make the cut for the v2.3 release. I was intending to get it in, but there was a much higher priority task that took my limited time (investigating why a user couldn't restore a specific RedHat system).

I am targeting another Rescuezilla release in February 2022 (only 2 months away). I'll get this done.

**Comment by Augusto7743** [comment]
Thanks for your reply.
Not demanding ...only trying understand if was or not added bzip2.
Have a nice week.

**Comment by shasheene** [comment]
Good news! This feature is now live in the [Rescuezilla Weekly Rolling Release](https://github.com/rescuezilla/rescuezilla/releases):
![bzip2](https://user-images.githubusercontent.com/1414379/175841473-3b909275-ae3e-40ac-a3ee-5d35d60fb318.png)
It will enter the "stable" build with Rescuezilla v2.4, once that is released.

@Augusto7743 please try it out and let me know if you have any suggestions. It uses pbzip2 (parallel bzip2).
