### ISSUE TITLE
Deploying VMDK files from XCP-NG?

### ISSUE THREAD

**Issue by admiralzeech** [rescuezilla/rescuezilla#310]
Hi, I've got a virtual machine running on XCP-NG.  It has the capability to export the VM as a VMDK file.

I place the VMDK file on a samba share.

However, when I browse to the samba share in rescuezilla, the VMDK file is not available to use for imaging?  My clonezilla images stored in the same share show up just fine.

I thought VMDK is supported for imaging?  Are there any caveats to that?

**Comment by shasheene** [comment]
Yes, VMDK files are supported. Internally restoring a virtual disk image first uses a tool named `qemu-nbd` to process the image into a standard Linux block device, then it can uses its existing cloning logic to "restore" it to another block device.

Make sure the ".vmdk" extension is lowercase, by the way.

The biggest caveat is `qemu-nbd` takes time to scan the image, and there's current a 10 second timeout. If you image happens to take longer than 10 seconds to scan it may not show up. This can happen on larger virtual disks and also very slow network shares. It will scan for 10 seconds and then give up. I recommend putting the image in its own subfolder and then clicking 'Browse' to navigate to it. Then you can easily see if it's being scanned.

Also another caveat is there can be some unreliability with `qemu-nbd` and Rescuezilla where `qemu-nbd` and the internal Linux driver can get into a weird state where images don't scan anymore -- especially if you force the Rescuezilla app to be killed when it's scanning an virtual machine image etc. At that point rebooting the entire Rescuezilla environment may be required to scan further virtual machine iamges using `qemu-nbd`.

I don't actually know how popular the virtual disk image feature is so it hasn't really been a big focus. I usually test with VDI files.

I have done a lot of tests mostly with VDI, including restoring Windows, Linux etc to real hardware and booting it. I've tested fewer VMDK examples, but the handling was be no different.

Let me know how you go!!

**Comment by admiralzeech** [comment]
Thanks for the reply.  I was able to get it working.  My filename was something like blablah.version.something.vmdk.


After renaming it to something.vmdk, it worked.

**Comment by shasheene** [comment]
If you had to rename the file to get it working then that's a bug, because VMDK images are just one file and there's no reason it shouldn't be robust for even complex filenames I just checked the exact logic and it shouldn't matter what the filename is except that it ends in "vmdk", also it's not case-sensitive I was wrong, so "VMDK" would have been fine:
```
for key in QemuImage.SUPPORTED_EXTENSIONS.keys():
    for extension in QemuImage.SUPPORTED_EXTENSIONS[key]:
        if filename.lower().endswith(extension):
            return True, extension
```

I think internally it still might have been the 10 second timeout, or another similar issue.

Regardless, glad it worked for you.
