### ISSUE TITLE
Add system-config-lvm to ISO

### ISSUE THREAD

**Issue by felipecrs** [rescuezilla/rescuezilla#314]
First of all, RescueZilla is amazing, and it has helped me a lot.

Today I came across the task of resizing the disk of one VM, and I used RescueZilla to get me to Gparted, which helped me to resize the physical partition.

However, it was a Logical Volume based setup, and to complete the task, I also had to resize the Logical Volumes.

As it can be seem here: https://askubuntu.com/a/489909/1074320

There is a GUI tool called system-config-lvm available in the Ubuntu repositories which allows such operations to be made from the UI.

I wonder if it would be a good idea to add it to the RescueZilla ISO.

Anyway, thank you!

**Comment by shasheene** [comment]
Thanks for the kind words. I will look into adding `system-config-lvm` for the upcoming Rescuezilla release, and update you on any decision as a comment below.

I still hope to integrate [`blivet-gui`](https://sourceforge.net/p/rescuezilla/discussion/discussion/thread/8b76ae5447/) which may also help you.

As I'm sure you're aware, if you have an internet connection you can install new tools in Rescuezilla by opening a terminal and running `sudo apt-get update && sudo apt-get install <package name>`. But these live in RAM so disappear when the live environment is restarted.

**Comment by felipecrs** [comment]
Thanks a lot for the fast answer!

> I still hope to integrate [`blivet-gui`](https://sourceforge.net/p/rescuezilla/discussion/discussion/thread/8b76ae5447/) which may also help you.

I never saw it, but on a quick glance, it seems to provide the ability of managing Logical Volumes as well.

If that's the case, I see no reason to add `system-config-lvm` then.

> As I'm sure you're aware, if you have an internet connection you can install new tools in Rescuezilla by opening a terminal and running `sudo apt-get update && sudo apt-get install <package name>`. But these live in RAM so disappear when the live environment is restarted.

Yes yes, that's right.

**Comment by felipecrs** [comment]
By reading this: https://www.linuxjournal.com/content/review-gui-lvm-tools

It says:

> The Red Hat has stopped to upgrade system-config-lvm, and there is no such package in CentOS 7/RHEL 7, Its replacement is blivet-gui.

So, I think there is no point to add system-config-lvm instead of blivet-gui. Closing this then. Thanks for letting me know about blivet-gui.
