### ISSUE TITLE
Allow change of success action (nothing / reboot / shutdown) while backup is running

### ISSUE THREAD

**Issue by PhoenixIV** [rescuezilla/rescuezilla#316]
The dropdown to change the behaviour may be removed from its current position completely and moved to the backup status screen. To me it adds additional value at no cost.

**Comment by shasheene** [comment]
Huh, moving that dropdown menu to the operation-in-progress page is a really great idea!

**Comment by shasheene** [comment]
Good news! This feature is now live in the [Rescuezilla Weekly Rolling Release](https://github.com/rescuezilla/rescuezilla/releases):
![post_operation](https://user-images.githubusercontent.com/1414379/175841482-4110a901-9612-42bb-8e5c-def54cdcde0c.png)
It will enter the "stable" build with Rescuezilla v2.4, once that is released.

Thanks again for this very sharp UI suggestion!

**Comment by PhoenixIV** [comment]
Thank you! :)
