### ISSUE TITLE
Single partition backup/restore broken in v1.0.5

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#32]
A user named 'coth' on the [AlternativeTo discussion forums](https://alternativeto.net/software/redo-backup-and-recovery/#post-59665) has suggested today that restoring secondary partitions using v1.0.5 does not work, but this functionality works with _Redo Backup and Restore_ v1.0.4.

While the [Limitations wiki page](https://github.com/rescuezilla/rescuezilla/wiki/Rescuezilla-Limitations) has always said "Rescuezilla v1.0.5 currently only officially supports backing up and restoring entire disks. Individual partition backup and restore is very immature right now and is not recommended. (to be fixed with #4).

However, I was unaware that the behavior in v1.0.5 was worse than it was in v1.0.4. If there is indeed a bug in v1.0.5 that wasn't in v1.0.4, rather than it fixed as part of the very broad 'Clonezilla drop-in compatibility' enhancement task (captured in issue #4, which will be completed at some indeterminate point in the future), this bug will be treated as a very high severity regression from existing behavior, and will be fixed as part of the next point release at high priority.

**Comment by shasheene** [comment]
@regs01 (aka coth), you wrote on AlternativeTo that

> 1.0.5 doesn't seem to work for me in many occasions. When I try to restore secondary partitions it says restoration is successful, but partition is actually broken. No partition manager can recognize it and GParted says - The file system is damaged. Restoring it via 1.0.4 works.

What exactly were you trying to backup? So these partitions were made on v1.0.4 and failed to restore on v1.0.5? You may be using different terminology to me, so could you further define what you mean when you call them 'secondary partitions'?

**Comment by regs01** [comment]
HDD with GPT and two Ext4 partitions.
I'm trying to backup second partition. 1.0.4 backs it up and restores well. 1.0.5 backs it up, but restore leads to file system damage. 1.0.4 is able to restore both backups made in 1.0.4 and 1.0.5.

**Comment by shasheene** [comment]
Can you provide more information about the unofficial Redo release you are using? The filename, a MD5 hash or at least a link to where you downloaded it from. I suspect you are using louvetch's Ubuntu 16.04 unofficial Redo update.

Just to clarify, it looks like you are describing potentially three separate issues:

1. Backup stuck at 0% "Just stays at 0% without saying anything" (from your AlternativeTo comment)
2. Restore stuck at calculating bitmap
3. Restore reports success, but "partition is actually broken. No partition manager can recognize it and GParted says - The file system is damaged."

As for item 1, it's very hard to debug without seeing logs. For sure Rescuezilla needs to display error dialogue boxes during these kinds of situations (to be fixed in #29). 

As for item 2, backups created using Nov 2019's Redo v1.0.5 cannot be restored using Nov 2012's Redo v1.0.4. Hopefully this accounts for this bug.

As for item 3, I recently ran into it while testing support for NVMe hard drives. The complete details are in #36, and the fix I have created for this will be part of v1.0.5.1 which will be released soon. In short, the root cause is the destination partition having the same device name as the original source partition, which causes the hard drive containing backup to be unmounted as the restore progress. This bug has been with Redo Backup and Recovery since the first release in June 2010, which is crazy! It only happens when the enumeration of the drives changes. Usually this means the drives in the machine have been inserted or removed, but I have seen the enumeration of the disks change between using Redo v1.0.4 and Redo v1.0.5 on the same machine with identical disks (I haven't yet looked into why, but now that the bug from #36 has been fixed, any changes in enumeration between releases should not matter).

**Comment by shasheene** [comment]
OK. It was very useful to learn that you were using one of the unofficial third-party Redo Backup and Recovery releases, rather than the official Redo Backup and Recovery v1.0.4 from 2012. You will pleased to here I have reproduced your issues and have a path forward, with fixes coming to v1.0.5.1.

Just to clarify, it looks like you are describing potentially three separate issues:

#### 1. Backup stuck at 0% (from your your AlternativeTo comment "Just stays at 0% without saying anything")

I have successfully reproduced this issue using the Sourceforge user louvetch's release from June 2017 (which was based on Ubuntu 16.04). This is most likely the release you have been using. The root cause is the 'sfdisk' utility in louvetech's release is using the deprecated '-x' argument which has been removed. Rescuezilla v1.0.5 handled this change, but louvetch's release runs the command without modification, leading to an empty file being written. The Rescuezilla v1.0.5 restore process assumes it is a v1.0.4 backup but then stalls because the data it was expecting from the sfdisk file is not there.

**Solution**: As part of v1.0.5.1, I will try test and fix Rescuezilla backwards compatibility for each of the unofficial third-party releases. There was actually quite a few unofficial third-party since 2012, but most are old enough that v1.0.4 should work. I will thoroughly test all of them.

#### 2. Restore stuck at calculating bitmap

As stated by the release notes for Nov 2019's Rescuezilla v1.0.5, backups created with v1.0.5 cannot be restored using Nov 2012's Redo v1.0.4 because the partclone application used internally has changed the way it works internally breaking backwards compatibility.

I have reproduced the "stuck at calculating bitmap" issue using v1.0.4 to restore a v1.0.5 backup, though I did get a "cat: write error: broken pipe" error message.

Please note, it's possible that some unofficial third-party Redo releases may be able to successfully restore using the original v1.0.4. Also it's possible the exact error behavior you see might change depending on the exact partition layout of the backup being restored, and whether or not the destination drive was erased or whether has some bytes left over that Redo Backup may be processing.

**Solution**: I will try and make the backwards compatibility clearer in the release notes, probably with a colored table. This "compatibility matrix" will already be required once the issue above is complete.

#### 3. Restore reports success, but "partition is actually broken. No partition manager can recognize it and GParted says - The file system is damaged."

I recently ran into it while testing support for NVMe hard drives. The complete details are in #36, and the fix I have created for this will be part of the next release, Rescuezilla v1.0.5.1. In short, the root cause is the destination partition having the same device name as the original source partition, which causes the hard drive containing backup to be unmounted as the restore progress. This bug has been with Redo Backup and Recovery since the first release in June 2010, which is crazy! It only happens when the enumeration of the drives changes. Usually this means the drives in the machine have been inserted or removed, but I have seen the enumeration of the disks change between using Redo v1.0.4 and Redo v1.0.5 on the same machine with identical disks (I haven't yet looked into why, but now that the bug from #36 has been fixed, any changes in enumeration between releases should not matter).

**Solution**: Already fixed by #36 as discussed in the paragraph above.

**Comment by shasheene** [comment]
@regs01, thank you for your help. [Rescuezilla v1.0.5.1 is now available (2020-03-24)](https://github.com/rescuezilla/rescuezilla/releases/tag/1.0.5.1) and should fix all the issues you were experiencing above, *except* being able to restore a v1.0.5/v1.0.5.1 backup using and older release.

Your bug reports has been very valuable in tracking down these bugs that affected you, and likely other users.

Let me know if you find any more bugs with Rescuezilla.

**Comment by regs01** [comment]
Tried 1.0.5.1. I cannot restore secondary partition. Just getting a message - Not restoring to source drive.

**Comment by shasheene** [comment]
Interesting, so you are trying to restore your backup image to the same drive it is stored on?

**Overwriting your source drive can be a very dangerous operation**, so v1.0.5.1 now blocks this by default. To enable this functionality, you need to remove a file. This can be done by closing Rescuezilla, opening a terminal and typing `rm /etc/rescuezilla/no_source_overwrite`, then opening Rescuezilla again.

> This file prevents a partition image being restored to the source device it resides on.
>
> Delete it allows this behavior with a confirmation dialog. It is recommended end-users do not delete this file.

Again, I need to stress that overwriting a backup image on the same drive it's stored on is a VERY dangerous operation that can potentially damage data. If you understand the risk, you can try it if  you want. Let me know the outcome either way!
