### ISSUE TITLE
The program cannot backup BTRFS partition

### ISSUE THREAD

**Issue by Studinsky** [rescuezilla/rescuezilla#335]
Tried on two laptops with btrfs partitions - result: error
##############    partclone.log   #########################
Partclone v0.3.13 http://partclone.org
Starting to clone device (/dev/nvme0n1p2) to image (-)
Reading Super Block

btrfsclone.c: btrfs library version = Btrfs v4.2.2
btrfsclone.c: Couldn't open file system

############   error output  ############
<b>Fehler beim Sichern der Partition</b> /dev/nvme0n1p2

The command used internally was:

partclone.btrfs --logfile /var/log/partclone.log --clone --source /dev/nvme0n1p2 --output - | pigz --stdout -6 | split --suffix-length=2 --bytes=4GB - /mnt/backup/2022-06-24-0615-img-rescuezilla/nvme0n1p2.btrfs-ptcl-img.gz. 

The output of the command was: Partclone v0.3.13 http://partclone.org
Starting to clone device (/dev/nvme0n1p2) to image (-)
Reading Super Block
couldn't open because of unsupported option features (10).
btrfsclone.c: Couldn't open file system
Partclone fail, please check /var/log/partclone.log !

**Comment by shasheene** [comment]
Sorry for your experience. This issue has been reported before (#168 and elsewhere) and is due to Rescuezilla having an old version of `partclone` from the Ubuntu repositories.

I am working on a new release, and including a version of partclone compiled from source is high on my agenda.

**Comment by shasheene** [comment]
Update: the latest version of `partclone` is now being built from source. It's available in Rescuezilla "Weekly" Rolling Release (2022-07-24) which will form the basis of Rescuezilla v2.4.

This fixes the compressed BTRFS issue.

CC: @Vyachean @cyberorganizer1 who reacted to a comment on this GitHub issue.

**Comment by cyborganizer1** [comment]
awesome, thank you :)

**Comment by cyborganizer1** [comment]
> Update: the latest version of `partclone` is now being built from source. It's available in Rescuezilla "Weekly" Rolling Release (2022-07-24) which will form the basis of Rescuezilla v2.4.
> 
> This fixes the compressed BTRFS issue.
> 
> CC: @Vyachean @cyborganizer1 who reacted to a comment on this GitHub issue.

awesome, thank you :)

**Comment by shasheene** [comment]
Closing issue as fixed in [Rescuezilla v2.4](https://github.com/rescuezilla/rescuezilla/releases)
