### ISSUE TITLE
Small QOL Suggestions

### ISSUE THREAD

**Issue by AE720** [rescuezilla/rescuezilla#341]
Let me know if I should make these separate or not. These were ideas that I had as I continue to use Rescuezilla.

It would be nice if the language and options were on one screen. I imagine it could look like the welcome screen on a Mac where the languages are on the bottom half of the screen and maybe clicking one will change the language of the menu in real time. 

Sometimes I'm backing up an image as I'm restoring another one and that gets caught in the scan, maybe there should be a flag on it to indicate it's being backed up that lets the scan ignore it.

On that note, I didn't see any plans to make scanning any faster, it can take quite a couple of minutes. One idea I had at the top of my head is to use checksums to compare a list that's cached in the folder you select and if the checksum is different, maybe rescan. However the issue is telling Rescuezilla what to expect and what to compare it to.

A custom reboot message. It currently says "Use shutdown -c to cancel" and instead of saying it will shut down at X time, you can just say X minutes.

Maybe there can be a fork of rescuezilla that can be booted via pxe, one that has authentication built in and the ability to use an "Answer File" to automate selections.

**Comment by shasheene** [comment]
Please create a bunch of separate GitHub issues with one for each suggestion, each with unique and descriptive title.

Then edit this one to focus on one of the suggestions. It'll keep discussion of any alternative approaches more focused.

**Comment by AE720** [comment]
Got it. My bad.
