### ISSUE TITLE
Screen Pixelates, Off-Center & Repates After RescueZilla Boot's to Menu

### ISSUE THREAD

**Issue by mbennette68** [rescuezilla/rescuezilla#347]
Hello,

I tried to image a Shuttle NC03U machine containing Ubuntu 16.04 LTS loaded in a 120GB SSD but was only able to reach the mai RescueZilla Menu screen.

The screen at that point was pixelated, vertically shifted and when I clicked on any part of the screen the mouse pointer acted like a 
digital brush, similar to those found in painting programs, meaning that it woud repaint the screen thus making the information on the actual menu unreadable. 

The link to the specs of the machine in question (i.e., Shuttle NC03U) can be found below:
[https://global.shuttle.com/products/productsSpec?productId=2111](https://global.shuttle.com/products/productsSpec?productId=2111)

Any thoughts, feedback or workarounds will be appreciated.

Thank you,
MB

**Comment by shasheene** [comment]
Sorry for the late reply.

Please try choosing the 'Graphical Fallback Mode' item from the boot menu (after selecting a language).

The recently released Rescuezilla v2.4 is based on Ubuntu 22.04 (Jammy), which may have fixed the issue. But for this particular machine, I doubt it.

Given the vintage of this specific machine, if Graphical Fallback Mode doesn't work, it's probably best to try Rescuezilla v2.3.1's alternative release based on Ubuntu 20.04 (Focal), which may yield a better experience.

**Comment by mbennette68** [comment]
Shasheene,

Thank you for the feedback. I tried the Graphical Fallback Mode and it did not work. No matter which mode I try, the fongs get reduced to a tiny specs so it is hard to even read the menu and then it pixelates.

I will try the older Rescuezilla v.2.3.1 and see if that works.

Thank you,
MB

**Comment by shasheene** [comment]
Sounds good. To be clear, make sure you pick the _alternative_ "Focal" based Rescuezilla v2.3.1 release at the bottom of the releases page under the Assets section the default "Impish" based release is what you're using.

**Comment by compicat** [comment]
Same here. This is about releases newer than Focal i guess. I was experiencing same stuff with v2.3.1 Implish too.

**Comment by mbennette68** [comment]
> Sounds good. To be clear, make sure you pick the _alternative_ "Focal" based Rescuezilla v2.3.1 release at the bottom of the releases page under the Assets section the default "Impish" based release is what you're using.

Yes, I downloaded the "Focal" based Rescuezilla v2.3.1. It seems this older Shuttle has a lot of video issues with newer tools, includingthe latest Resuezilla, Macrium's and EaseeUs's latest releases. I usually try these tools on VMWare or VirtualBox but they also would not boot correctly. 

My original goal was to transisition some of these images into a VirtualMachine, tweak them, install what I need based on the hardware of any PC, including ARM-based devices then clone the VM install back into an image and use that to image any particular target device but this is becoming very difficult at the momen so I'm having to experiment with the actual hardware which is time consuming not to mention difficult since this pc is vintage and hard to find at a discount.

Thank you,
MB
