### ISSUE TITLE
error compiling rescuezilla on jammy

### ISSUE THREAD

**Issue by dacorsa** [rescuezilla/rescuezilla#356]
compiling ruscuezilla on jammy i see some errors:

1) fatal: No URL found in .gitmodules per il percorso del sottomodulo 'src/third-party/partclone.v0.2.43'

2) /bin/sh: 1: /app/rescuezilla/src/third-party/util-linux/autogen.sh: not found

How can i solve?

Thanks, best regards

**Comment by shasheene** [comment]
Looks like on a clean git clone, the git submodules are no longer correctly specified.

For Rescuezilla v2.4 release, I was modifying submodules to support providing the latest partclone version in Rescuezilla. 

**Rescuezilla v2.4 was released prematurely and introduced several bugs, apparently including this one.**

So you're definitely correct the submodule is broken for `partclone.v0.2.43`. That submodule is an old version of partclone that I provided for backwards compatibility and it has been removed from newer versions of Rescuezilla.

I'll try and fix this tonight and give you an update.

**Comment by dacorsa** [comment]
thanks now works, but last command says:
sudo make focal: (no make file found)
make: *** Nessun obiettivo specificato e nessun makefile trovato.  Arresto.
Why?
Best regards

**Comment by dacorsa** [comment]
i change maybe to the correct dir:
cd /mnt/ramdisk/rescuezilla/
sudo make jammy

but i have same error:
 dpkg-genbuildinfo -O../graphical-shutdown_2.4-1_amd64.buildinfo
 dpkg-genchanges -O../graphical-shutdown_2.4-1_amd64.changes
dpkg-genchanges: Informazioni: including full source code in upload
 dpkg-source --after-build .
dpkg-buildpackage: Informazioni: Caricamento completo (sorgente originale incluso)
make[1]: uscita dalla directory «/mnt/ramdisk/rescuezilla/src/apps/graphical-shutdown»
mkdir --parents /mnt/ramdisk/rescuezilla/build/jammy.amd64/util-linux /mnt/ramdisk/rescuezilla/build/jammy.amd64/chroot/usr/sbin/
cd /mnt/ramdisk/rescuezilla/build/jammy.amd64/util-linux && /mnt/ramdisk/rescuezilla/src/third-party/util-linux/autogen.sh
/bin/sh: 1: /mnt/ramdisk/rescuezilla/src/third-party/util-linux/autogen.sh: not found
make: *** [Makefile:68: sfdisk.v2.20.1.amd64] Errore 127
/mnt/ramdisk/rescuezilla master#

**Comment by shasheene** [comment]
Here's the fastest fix: change line 36 of the Makefile:

```
-jammy: deb sfdisk.v2.20.1.amd64 partclone-latest partclone-utils partclone-nbd $(buildscripts)
+jammy: deb partclone-utils partclone-nbd $(buildscripts)
```
then run `make jammy`. That will build.

The errors you are seeing is due to the submodules not building. I made some changes to the git submodule for v2.4 and as mentioned, on a clean clone it doesn't build. I'm working on Rescuezilla right now and I hope to fix it properly tonight.

**Comment by dacorsa** [comment]
Thanks now works perfectly!
PS: change the dir in README
cd /mnt/ramdisk/rescuezilla/
and after run
sudo make jammy

ciao

**Comment by dacorsa** [comment]
Thanks now works perfectly!
PS: change the dir in README
cd /mnt/ramdisk/rescuezilla/
and after run
sudo make jammy

ciao

**Comment by shasheene** [comment]
I'll keep this open until I fix the underlying submodule issue :+1:

**Comment by shasheene** [comment]
I've fixed the submodule problem, and also fixed Focal and Impish build too, so everything should work from `origin/master`.
