### ISSUE TITLE
Hungarian Translation - Finished. (HU)

### ISSUE THREAD

**Issue by PizzaProgram** [rescuezilla/rescuezilla#384]
I've just finished the Hungarian translation. (Hu = HUN = Magyar )  
https://hosted.weblate.org/translate/rescuezilla/rescuezilla/hu/  
 so you may include it in the next release.
  
It should be listed as: 
 - "Magyar / Hungarian tegező" .
 (if there is not enough space, you can cut off the _"tegező"_ part.
 
Hungarian language has two forms: 
 - a direct friendly = _"tegező"_ : (Hey You, press that button! ) <  **I've translated in this form,** 
 - and an "official" = "magázó" : (Dear Sir, if that button is being pressed ... ) -- this is called in Hungary: "suffering form of grammar".  

If the codepage is not UTF8, please set Win1250 or [CP852](https://en.wikipedia.org/wiki/Code_page_852) .

If it is possible, it would be nice, if choosing this language would:
 - **Automatically set Hungarian keyboard layout too !**

**Comment by shasheene** [comment]
Great work, I'll integrate this tonight and get you a custom build to use until the next release.

**Comment by PizzaProgram** [comment]
Thanks, but no need for custom b.
Enough for the next release.
