### ISSUE TITLE
SSH Destination Port problem

### ISSUE THREAD

**Issue by chienbinhso14** [rescuezilla/rescuezilla#385]
SSH Destination cannot change from "Domain"
![image](https://user-images.githubusercontent.com/24795386/192970307-3b6a4603-f4cf-47c7-ae7e-345bf508f486.png)
![image](https://user-images.githubusercontent.com/24795386/192970634-c589f284-396f-4bc8-a9a8-60bf0d0a8c83.png)

**Comment by Deanosim** [comment]
I have the exact same problem, I can't enter my custom port when trying to backup which means I can't use rescuezilla for backups.
![image](https://user-images.githubusercontent.com/4834976/206436346-22e56bab-86c2-43ce-8f87-debd73384e1f.png)
Only seems to happen on the backup menu on the browse image menu it works.

**Comment by shasheene** [comment]
Yep, I screwed it up on Rescuezilla v2.4 when I introduced that feature sorry. Forgot to create a ticket for it.

If you just need port 22, use Rescuezilla v2.3.1 for now.

Fix coming in Rescuezilla v2.5, exact release date not yet known.

I have a bunch of unpublished changes related to Rescuezilla I was working on recently.

**Comment by shasheene** [comment]
I've tested the fixed and merged it, but keeping GitHub issue open until next version of Rescuezilla (almost certainly v2.4.2, not v2.5)

**Comment by shasheene** [comment]
Change available from [Rescuezilla v2.4.2](https://github.com/rescuezilla/rescuezilla/releases/latest)
