### ISSUE TITLE
Include flashrom package

### ISSUE THREAD

**Issue by Tarek-Hasan** [rescuezilla/rescuezilla#388]
As a system recovery software, rescuzilla should include flashrom. Cause while performing recovery often times one face with problem which can only be solved by flashing, upgrading or downgrading firmware. Including it in a live system will make it easier.

https://www.flashrom.org/Flashrom
https://github.com/flashrom/flashrom

**Comment by shasheene** [comment]
`flashrom` now available from [Rescuezilla v2.4.2](https://github.com/rescuezilla/rescuezilla/releases/latest)
