### ISSUE TITLE
availability of debian package for rescuezilla

### ISSUE THREAD

**Issue by pdcq** [rescuezilla/rescuezilla#405]
I have my own custom Ubuntu ISO (based on the Official Ubuntu Jammy Desktop LiveCD).
I would like to update the rescuezilla package which I had previously taken from the github repository.
In your documentation you state:
Download deb package the [releases page](https://github.com/rescuezilla/rescuezilla/releases/latest) (it's under the 'Assets' section right at the bottom)

But there's no .deb package available in the assets section, only the ISO and sources (which require many dependencies). Can you please please provide this back on github for us to use.
This is not an "info" issue, but a "missing file"!

**Comment by Ludo-code** [comment]
I think this issue can be closed because of now deb package have been released to the latest release.
https://github.com/rescuezilla/rescuezilla/releases
