### ISSUE TITLE
Support for Windows Extended Partitions

### ISSUE THREAD

**Issue by FluorescentGreen5** [rescuezilla/rescuezilla#442]
I was trying to backup a drive with an "extended" partition, but found that Rescuezilla will either error out (I can't remember the error message but I know it was a pretty vague one) or freeze when it tries to image it. Any chance you could add support for Windows extended partitions?

I was using Rescuezilla 2.4.1 Jammy for both attempts at backing up the drive.

**Comment by shasheene** [comment]
Partitions using legacy DOS partition table with an “extended” partition is one of the core situations that all Rescuezilla releases are tested against.

Rescuezilla's imaging should certainly not error out or freeze when making a backup of an extended partition.

Could you please send the `clonezilla-img` file either here or to rescuezilla at gmail and I'll take a look at what went wrong.

**Comment by FluorescentGreen5** [comment]
My bad, I didn't realise that the extended partition I was backing up was too big to be backed up to the destination drive. Although an error message telling me that the destination drive ran out of space would be a good fix.
