### ISSUE TITLE
[Question] Can the backup disk be smaller?

### ISSUE THREAD

**Issue by RasheedAZ** [rescuezilla/rescuezilla#447]
Hi Shasheen. Thanks for developing this awesome and most useful application :)

Sorry if this is a dumb question but I'd really appreciate it if you could answer it: 

I have a PC with a 512 GB drive which is only ~100 GB full. Can I back it up to a 128 GB USB stick with Rescuezilla?

After that, I want to restore that backup to a few other identical (512 GB) PCs.

**Comment by shasheene** [comment]
Yes, that should work fine.

The backup image is created in a "filesystem-aware" way, and additionally is compressed, so your backup image folder will only be about ~100GB in size.

Though I should note if your destination disk for the backup (your 128GB USB stick) runs out of space, Rescuezilla v2.4.2 (still) doesn't produce a user-friendly error -- it just silently stalls right now.
