### ISSUE TITLE
Improve ability to restore individual partitions

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#46]
For all versions of _Redo Backup and Recovery_, the ability to backup and restore individual partition has not been mature.

Since _Redo Backup and Recovery_ was revived in November 2019 by a new maintainer under the Rescuezilla name, [this limitation has been clearly listed](https://github.com/rescuezilla/rescuezilla/wiki/Rescuezilla-Limitations) with the statement that "**Rescuezilla officially supports backing up and restoring entire disks. Individual partition backup and restore is very immature right now and is not recommended**".

In the past, some [users](https://sourceforge.net/p/redobackup/discussion/1169663/thread/93941553/) have asked detailed questions about this on the Sourceforge forum. The task to complete this was originally part of #4 (Clonezilla support), but it makes a lot more sense to improve this situation as a separate GitHub issue (this one), so it can be referenced in these forum topics.

The problem is:

* There is no page to select individual partitions during a restore process (which makes it all or nothing)
* The entire partition table is always overwritten.

However, there is a page to select partitions to backup. This makes it possible to to backup a single partition and IF the partition table hasn't been changed, there is an extremely rudimentary ability to surgically restore individual partitions. However, if the partition table HAD changed (eg, restoring to a different disk), the existing partition table will differ and it being overwritten is very dangerous.

Since the original version of _Redo Backup and Recovery_ in 2010, this issue may have caused some users big issues. Since the inception of Rescuezilla, the whole disk backup/restore limitation has always been made as clear as possible.

The ability to select individual partitions to restore and not overwrite the partition table is very important to implement as soon as possible, because realistically not everyone will read the limitations page or the FAQ.

**Comment by shasheene** [comment]
Feature implemented in [Rescuezilla v2.0](https://github.com/rescuezilla/rescuezilla/releases/latest).

**Comment by candrapersada** [comment]
why is 'Overwrite partition table' selected by default for the latest Rescuezilla?

**Comment by shasheene** [comment]
Overwriting the partition table has always been by default.

In all versions before Rescuezilla v2.0 there was no ability to select individual partitions to restore, so the partition table was always overwritten. Since Rescuezilla v2.0 there is a page to select which partitions from the backup to restore, with an option to not overwrite the partition table.

Most users will want to backup and restore their entire computer (eg, to a new hard drive). The ability to not overwrite the partition table but instead map the partitions manually is a very advanced operation. Untick and retick the option to read some information to determine which option is right for you. (Side note: at some point I will make sure the help text is always displayed, as intended)

**Comment by candrapersada** [comment]
Add ability to select all/deselect all partitions for individual partition backup and restore.

**Comment by shasheene** [comment]
You already raised that issue here: https://github.com/rescuezilla/rescuezilla/issues/145#issue-756915710
