### ISSUE TITLE
[critical] Users report failed clone (and backup) caused working Windows to break

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#466]
I've received [reports](https://sourceforge.net/p/rescuezilla/discussion/support/thread/031dce6400/) [recently](https://sourceforge.net/p/rescuezilla/discussion/support/thread/61bce0299f/) of Rescuezilla being used to create a backup image or clone of a working Windows environment that happens to fail with an error message.

**But when a user attempted reboots back into Windows it enters auto-repair and was unable to repair itself.**

This is a critical severity error report.

A backup image that fails to be created is to be expected (it happens often due to hibernated NTFS filesystem requiring a reboot) but it is intended to be a **completely read-only operation for the source disk, so should _never_  cause a failure next boot**.

A failed direct 1-to-1 _clone_ is a more complicated situation: like the backup case the source disk is still not intended to be modified, but the destination disk _is_ expected to have bootloaders and partition identifiers be a duplicated from the source. Therefore upon a failed clone it's more understandable that upon a reboot (if the user isn't instructed to explicitly disconnect the destination drive or otherwise format it) that the operating system's bootloader could get confused and conduct a failed autorepair.

As [documented on the first report, my tasks are to](https://sourceforge.net/p/rescuezilla/discussion/support/thread/031dce6400/#71ab/5501/82a4/49fb/07c1):

> 1. Keep trying to develop a reproducible failure case for this
> 2. Determine the root cause (my theory is still the Windows bootloader's auto repair put itself into a relatively persistent bad state when booted with original source filesystem and a specific failed clone one present)
> 3. Identify preventative solutions for Rescuezilla frontend (improving the warning messages about the dangers of booting with cloned disks present certainly seems reasonable)
> 4. Identify a series of steps on how to resolve such a situation since Windows bootloader autorepair failed (eg, boot from Windows boot media, go to command-line and run a series of steps manually)

**Comment by shasheene** [comment]
> [Rescuezilla backup and clone operations are] intended to be a completely read-only operation for the source disk

Since Rescuezilla v2.3 (2021-12-24) until Rescuezilla v2.4.2 this has certainly **not** been true, for NTFS filesystems used in Windows, due to the step 'Run ntfsfix and don't schedule an NTFS consistency check':

`ntfsfix --clear-dirty /dev/sda3`:
```
Mounting volume... OK
Processing of $MFT and $MFTMirr completed successfully.
Checking the alternate boot sector... OK
NTFS volume version is 3.1.
NTFS partition /dev/sda3 was processed successfully.
```

This step (which modifies the source disk) is almost certainly the root cause of the issues those users experienced.

From the `ntfsfix` manual:
```
       -b, --clear-bad-sectors
              Clear the list of bad sectors. This is useful after cloning an old disk with bad sectors to a new disk.

       -d, --clear-dirty
              Clear the volume dirty flag if the volume can be fixed and mounted.  If the option is not present or the volume cannot be fixed, the dirty volume flag is set to request a volume checking at next mount.
```

**Comment by Daiking70** [comment]
Hi, I formatted the PC this morning 03/31/2024. I created the 64 GB Scandisk USB stick with rufus-4.4 and also with balenaEtcher-Portable-1.18.11. In both cases it gives me an error and doesn't boot and the PC turns off.
here's what appears to me:

Failed to open \EFI\BOOT\MMX64.efi -Not Found
Failed to load image ▯▯: Not Found
Failed to start HokManager: Not Found
Something has gone seriously wrong: import_mok_state () failed : Not Found

The version I put is Windows 11 Pro 23H2, the backup file is the one posted on the rescuezilla-2.4.2-64bit.jammy.iso site

It doesn't work, I'm freaking out.

**Comment by shasheene** [comment]
@Daiking70 Is the issue you're talking about is related to not being able to boot a Rescuezilla USB stick, correct? The error appears to be indicating your BIOS isn't able to boot Rescuezilla because it currently doesn't list the expected bootloader (there's an unrelated bug for this), and your symptoms aren't the ones discussed in this issue.

Or were you able to use Rescuezilla to create a Windows backup or clone, and then had an issue when the Rescuezilla USB stick was removed?

**Comment by Splatink** [comment]
I can confirm Windows was not bootable for me either after restoring from a backup

**Comment by shasheene** [comment]
@Splatink  can you please provide details on what you did to restore your backup? Is this with Rescuezilla v2.5 (Noble)?

Did you create your backup using Rescuezilla v2.5 or with an earlier version? Does your backup verify successfully?

**Comment by shasheene** [comment]
Ahh super sorry for really terrible experience. Thanks for reporting it.

This is a very frustrating bug because I haven't been able to reproduce it, but it's clearly majorly impacting some users.

**Comment by shasheene** [comment]
A [user](https://sourceforge.net/p/rescuezilla/discussion/support/thread/2edbf2e19b/?limit=25#4b46) experienced this issue with what sounds like the definite association with the NTFS hibernate logic that modifies the source disk as described above. That's enough for me to remove the only modification of the source disk:

> First attempt was a fail..
> This caused source drive partitions corrupted and i needed to reclone the source disk from another machine with same hardware and windows install.
> 
> i think i know ehat caused the issues. When we disconnected the pc we didnt properly shut it down and windows is scheduled to a repair check as the error said also.
> 
> somhow the new 250g ssd were part of source disk so bios started from that disk..
> 
> strange.
>
> attaching pic on of many errors.
>
> ![20240826_094955](https://github.com/user-attachments/assets/055be025-f4b8-4194-ba84-17859d0d9b91)

**Comment by shasheene** [comment]
Rescuezilla v2.5.1 has now been released: https://github.com/rescuezilla/rescuezilla/releases/latest

It has removed the only known modification of the source disk that Rescuezilla makes backup and clone operations: the usage of `ntfsfix --clear-dirty` described above. From the Rescuezilla v2.5.1 changelog:

> * Stops running the `ntfsfix --clear-dirty` on NTFS filesystems on the SOURCE DISK during backup and clone operations ([#466](https://github.com/rescuezilla/rescuezilla/issues/466))
>   * Running this command (the only command in Rescuezilla that modifies the source disk) appears to be the root cause of a critical severity error that impacted a small number of (hibernated) Windows disks since the command was added in Rescuezilla v2.3 (2021-12-24) where creating a backup image or clone appears to cause some kind of corruption that can break the Windows boot with a Blue Screen of Death, possibly due to corruption in the Windows BCD (Boot Configuration Data)
>   * However, I still have not been able to reproduce the error in despite many hours of testing
>   * Removing this command will likely mean more 'hibernated NTFS disk' errors on backup or clone of Windows disks if not booting into Rescuezilla with the 'Restart' Start Menu command -- but removing the apparently dangerous command is obviously worthwhile

Separately, a user on the Sourceforge forum [reports](https://sourceforge.net/p/rescuezilla/discussion/support/thread/031dce6400/#f479) they were able to fix the issue using the following instructions:

> Correction. the above video solution did work. it just required two restarts after completing the suggested CMD operations from a live booted flashdrive of ventoy 1.0.99 running the latest windows 10 64 bit ISO image 22H2. 
> 
> I copied the windows ISO to the storage partition on a 64 GB sandisk cruzer USB, that had ventoy 1.0.99 flashed to it. 
> I plugged in the USB and booted the windows iso via wimboot from the ventoy menu.
> I then followed the instructions in the video exactly. Here is the link to the video below once again. 
> I rebooted twice. My problem was resolved. What a relief. 
> 
> https://www.youtube.com/watch?v=eHGsI3CUlgs


As noted in the changelog, I haven't been able to reproduce the issue despite many hours of testing.

The source disk is no longer modified by the `ntfsfix --clear-dirty` during backup and clone operations, which appears to be the only possible root cause.

Therefore, closing this issue now.
