### ISSUE TITLE
Implement support for device-device operation ("cloning")

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#47]
Rescuezilla has never supported what Clonezilla calls "device-device" mode: copying one hard drive directly to another (commonly called "disk cloning"). Many users have called for this function.

Instead, Rescuezilla currently only supports what Clonezilla calls "device-image" backup and restore. This means backing up a source drive to a bunch of files, and then later restoring these files back to a disk and is often called "disk imaging". This means during a backup process, Rescuezilla's destination is limited to a hard drives containing filesystem that Rescuezilla can write files to.

Supporting the device-device "disk cloning" mode is a key part of implementing #4 (making Rescuezilla a drop-in replacement to Clonezilla), but it makes a lot of sense to treat this feature as a separate issue that can be implemented before all of #4 is implemented.

Many users have suggested Rescuezilla's simplicity is why they prefer using this tool. The design of device-device operation must be done very carefully to avoid over-complicating the user interface.

This issue will not be a high priority until other issues on the backlog are completed. The overall effect of a hard drive clone can still be achieved using Rescuezilla's existing mode by using a third hard drive to temporarily store files.

**Comment by shasheene** [comment]
**Mid-October 2020 update:**  Rescuezilla v2.0 has adds initial drop-in interoperability with Clonezilla. This has mainly been focused at the disk imaging side of things.

Marketing Rescuezilla as drop-in interoperable with Conezilla understandably brings [renewed](https://sourceforge.net/p/rescuezilla/discussion/support/thread/9a24dbd134/) interest in other Clonezilla features like cloning, which Rescuezilla does not yet support.

Adding this feature is not particularly difficult, but there are many higher priorities.

I have highlighted this in the [frequently asked questions page](https://rescuezilla.com/help.html). I should also mention readers may be interested in some of the other items in the dwindling list of [Rescuezilla Limitations](https://github.com/rescuezilla/rescuezilla/wiki/Rescuezilla-Limitations).

**Comment by candrapersada** [comment]
or use Gparted to copy partition to partition

**Comment by shasheene** [comment]
True but some people find Rescuezilla's wizard-based interface easier to use!

**Comment by shasheene** [comment]
Hi everybody,

Sorry to bother you all. I am tagging you in this post since you all have been interested in translating Rescuezilla.

**Rescuezilla now uses Weblate for translations: https://hosted.weblate.org/projects/rescuezilla/#languages**

Weblate should make it _much_ easier for people to translate Rescuezilla as the project grows to hundreds of supported languages.

Rescuezilla v2.2 will be released in late-May 2021 (less than 2 weeks from now). I've added the highly-requested 'Cloning' mode (for direct device-to-device copying) among many other features. I have also reworded many of the English sentences to be as clear as possible for newbie users, so some of the translations might have become less accurate.

**I would greatly appreciate if you reviewed and translated Rescuezilla into any languages you're familiar with: https://hosted.weblate.org/projects/rescuezilla/#languages**

Thanks again for your support, @pfrouleau, @caralu74, @vinicioslc, @zeit439, @emircankavas, @tkatsageorgis ,@AE720, @FX8350, @mzky, @XuCpeng and @AliensInc

- Shasheen Ediriweera (developer of Rescuezilla)

**Comment by TheAlienDrew** [comment]
@shasheene Shouldn't the FAQ page be updated? https://rescuezilla.com/help.html#:~:text=q%3A%20does%20rescuezilla%20support%20cloning%3F

**Comment by shasheene** [comment]
@TheAlienDrew Yes, but while this cloning feature has been implemented it will be released as part of Rescuezilla v2.2 scheduled for late-May 2021 (a bit more than a week from now).

For time efficiency, I am updating the FAQ for Rescuezilla v2.2 in one go.

But until Rescuezilla v2.2 is released, the "Rescuezilla does not yet support cloning"  answer will still be relevant.

**Comment by shasheene** [comment]
**Update June 2021**: [Rescuezilla v2.2](https://github.com/rescuezilla/rescuezilla/releases) has been released.
