### ISSUE TITLE
Gave 2.4.2 only 1G of RAM: crashed because lightdm didn't start

### ISSUE THREAD

**Issue by skirsch** [rescuezilla/rescuezilla#477]
This is probably more of an ubuntu bug, but I gave Rescuezilla only 1G of RAM and it didn't make it through the boot.

You'd think there would be a check for this and a warning to the user, but there isn't.

Wasted 15 minutes before I figured it out, but a more helpful error message about insufficient RAM would have been nice.

**Comment by shasheene** [comment]
Yeah a warning for low RAM during boot would be a good piece of polish -- largely for VM users, but for very old 32-bit systems.

The minimum system requirements of Rescuezilla is still listed as "1GB RAM (2GB recommended)" based on the last time I checked. I should retest this and likely bump it to 1.5GB or 2GB.

**Comment by skirsch** [comment]
:)

**Comment by skirsch** [comment]
probably a really bizzare case for sure. might be worth addressing if it happens to others. this was just an odd case that should have been caught.
