### ISSUE TITLE
RZ 2.5 Noble: Error creating image when selecting only one partition of source disk

### ISSUE THREAD

**Issue by nelsonhef** [rescuezilla/rescuezilla#482]
Hi, i tried to make an uncompressed image of just one partition of the source disk and it didn't start. Running RescueZilla from the terminal i got the following error

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/backup_manager.py", line 129, in do_backup_wrapper
    self.do_backup()
  File "/usr/lib/python3/dist-packages/rescuezilla/backup_manager.py", line 149, in do_backup
    if len(self.partitions_to_backup) == 1 and self.partitions_to_backup[0] == "all":
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 0
 Moving to mode=Mode.BACKUP on page Page.BACKUP_PROGRESS

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rescuezilla/gtk_ui_manager.py", line 117, in _completed_operation
    callable_fn(succeeded=succeeded, message=message)
  File "/usr/lib/python3/dist-packages/rescuezilla/backup_manager.py", line 1036, in completed_backup
    with self.summary_message_lock:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BackupManager' object has no attribute 'summary_message_lock'
``` 

When all source partitions are selected, the image creation proceeds normally.

Using rescuezilla-2.5-64bit.noble.iso, before that, i was using rescuezilla-2.4.2-64bit.jammy.iso which worked fine.

**Comment by antdude** [comment]
I was trying out Rescuezilla v2.5 (Noble) v2.5 in my updated 64-bit W10 Pro VirtualBox's guest VM  and wanted to back up the 50 MB partition into a bigger partition in the same virtual drive. It also got stuck too. I think this is the same problem as this bug report. I don't remember this problem in v2.4.2 when I did a quick test.

**Comment by shasheene** [comment]
Rescuezilla v2.5.1 has now been released with this issue fixed: https://github.com/rescuezilla/rescuezilla/releases/latest
