### ISSUE TITLE
Problem uploading the image

### ISSUE THREAD

**Issue by uguilherme** [rescuezilla/rescuezilla#513]
I'm facing an issue when uploading the image to another computer. Initially, I created the image from the computer I wanted, which is actually the same model where the image would be applied. The image creation was done without any problems. However, when I try to restore the image and then start the operating system, the Windows blue screen appears, preventing the system from booting. I’ve already disabled BitLocker, but that didn’t solve the issue. Can you help me?

**Comment by shasheene** [comment]
Sorry forgot to reply to this @uguilherme. Were you able to resolve the problem?

Sounds similar to the issue reported here https://github.com/rescuezilla/rescuezilla/issues/518 

ie, there could be a bug in Rescuezilla v2.5.1 where it may not be cloning some key files on Windows 11 disks.
