### ISSUE TITLE
Cant clone after shrinking partition

### ISSUE THREAD

**Issue by hugo9655** [rescuezilla/rescuezilla#519]
Im trying to clone an OS drive with windows on it to a smaller drive thats empty. After shrinking the size of the partition on the source drive, it still wont clone to the smaller drive.

I think it has something to do with how the partitions are structured, since rescuezilla mentions shrinking the "last partition", but there is no last one to shrink or grow, just the bulk of the storage space thats in the middle of the other partitions.

Is there anything I can do?

**Comment by shasheene** [comment]
Yes, Rescuezilla needs the end of the last partition on source disk to be within the destination disk size as documented here: https://github.com/rescuezilla/rescuezilla/wiki/HOWTO:-Restoring-to-a-smaller-disk.-Eg,-1000GB-HDD-to-500GB-SSD

There may be a small partition that needs to be shifted.

As per those instructions, you may have a backup image created before you did the shrinking. If you do, please upload the `sda-pt.sf` (or similar file ending in `-pt.sf`) so I can examine it. It contains the partition table file. Even better if you have a `-pt.sf` file from after the shrinking.

I should note, I have [seen situations where there's actually a weird invisible/phantom partition](https://sourceforge.net/p/rescuezilla/discussion/support/thread/fcbd00f76c/?limit=250#0a5a) that can block the process -- some weird leftover metadata. But that's probably not the case here.

There's probably a partition you need to use GParted to shift. On modern disk types (specifically GPT formatted disks) should be safe under all circumstances, but create a backup image before making any changes (if you haven't already).

(Sorry for Rescuezilla's bad user-experience in this situation. Having Rescuezilla automatically intelligently rearrange the partitions and avoiding the user needing to do anything manual here is the goal -- I know how to do it I just need to rewrite the internals of Rescuezilla to make it happen)

**Comment by shasheene** [comment]
> Error message said "Error restoring partition /dev/sda3 to /dev/sda3" and "NTFS Volume '/dev/sda3' is scheduled for a check or it was shutdown uncleanly. Please boot Windows or fix it by fsck".

This indicates you need to boot into the source disk and use the Windows start menu with the 'Restart' into Rescuezilla, because the NTFS filesystem is marked as hibernated of scheduled for filesystem check.

When Windows boots it will do a filesystem check, and when you use 'Restart' it will make sure it doesn't go into hibernated state but leave the disk in an accessible state for Rescuezilla to operate on.

**Comment by bordam** [comment]
> Error restoring partition /dev/sda3 to /dev/sda3" and "NTFS Volume '/dev/sda3' is scheduled for a check or it was shutdown uncleanly. Please boot Windows or fix it by fsck

If anyone stumbles upon this and rebooting doesn't fix the issue, you must run chkdsk on windows. You can google it to see how it's done.

Solution from https://sourceforge.net/p/clonezilla/discussion/Help/thread/b3f11e2133/
