### ISSUE TITLE
Installation corrupts after booting a certain amount of times

### ISSUE THREAD

**Issue by hugo9655** [rescuezilla/rescuezilla#526]
I'm not entirely sure whats happening, but after booting into resucezilla several times, it seemingly corrupts and becomes completely unusable. Applications dont open, menu options break (like shutdown), and you're unable to perform actions like backups (shows weird errors each time, like one about backup_manager.py).

I've had to re-flash rescuezilla a few times because of this.

**Comment by shasheene** [comment]
Do you experience this on a different USB stick? Try a different USB port.

I suspect it's most likely after booting the USB stick was knocked loose slightly. It's possible to select 'Load USB into RAM' after selecting a language which allows the USB stick to be completely disconnected, which remove the risk of a momentary disconnection breaking things.

Rescuezilla's root filesystem continues to be inside an ISO9660 CD-ROM style filesystem that's _mounted_ as read-only. But the USB stick device is accessible within the normal Linux environment within Rescuezilla. If the USB stick is somehow modified by a boot that would be very interesting, but I can't imagine how. Unlike filesystems like EXT4, ISO9660 doesn't even have a last-mount timestamp that gets modified.
