### ISSUE TITLE
False menu items such as "(Windows Boot Manager, )" with Rescuezilla v1.0.5.1

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#69]
A [user](https://github.com/rescuezilla/rescuezilla/issues/27#issuecomment-629901913) recently reported not being able to see an "ADATA m.2 NVMe SSD source drive", claiming to have seen this issue on Rescuezilla v1.0.5.1. The user uploaded a [log file](https://github.com/rescuezilla/rescuezilla/files/4646547/rescuezilla.20200518T133101.txt) when requested.

From this log file, it can be inferred that Rescuezilla v1.0.5.1 is indeed being used, as an ISO9660 filesystem labelled Rescuezilla sized at 666MB is present (side note: added  https://github.com/rescuezilla/rescuezilla/commit/5ab9dd7dc4f14a1f7bd9c996b939d93f493779f5 in response to this bug report, so that in future such inferring of the version from the log won't be needed).

The key part of the log appears to be right at the start (`lsblk: /dev//dev/nvme0n1p1: not a block device`). This indicates the output of either `os-prober` or `fsarchiver probe` command (which provides the data used in a call to `lsblk --noheadings --output=pkname --nodeps /dev/$input_partition`) has has been prepended with "/dev/".

Further examination suggests the root cause is `os-prober`, having been broken when NVMe support was added (regressions like these can be fixed with unit tests, which are planned with #49).

**Comment by shasheene** [comment]
@billlum

Thanks for reporting the issue. Did you see a screen similar to the image below? 

![os-prober nvme issue](https://user-images.githubusercontent.com/1414379/82346682-ee4a1c80-9a35-11ea-9102-2ff3077f43e8.png)

Rescuezilla v1.0.5.1 is not merging the menu entries. For now, **it should be possible to workaround the issue by selecting the menu item starting with "Drive" that corresponds to the correct hard drive capacity.**

Rescuezilla v1.0.6 will be released in a few weeks with this issue (and many others) fixed.

**Comment by billlum** [comment]
@shasheene thanks to your advice, I completed the backup successfully!!
Btw, I'm a Patreon contributor and looking forward to your great work in v1.0.6!

**Comment by shasheene** [comment]
@billlum 

I thought I had recognized the name, but I couldn't remember where from. Thanks for your generous support!

As you may have seen, there are many bug fixes coming in [Rescuezilla v1.0.6](https://github.com/rescuezilla/rescuezilla/projects/2#card-38512940), but from the log file you provided it looks like these issues won't affect your Windows backup at all.

Let me know if you have any issues.

**Comment by billlum** [comment]
FYI, I also just visited Adelaide back in February. Very impressed and
really enjoyed my time there! The Pasadena Foodland there is so impressive!!

billlum

**Comment by shasheene** [comment]
This issue has been fixed by [Rescuezilla v1.0.6](https://github.com/rescuezilla/rescuezilla/releases/latest).
