### ISSUE TITLE
Cannot create Rescuezilla v1.0.6 USB using YUMI multiboot (rather than balenaEtcher)

### ISSUE THREAD

**Issue by shasheene** [rescuezilla/rescuezilla#88]
It has been [reported that creating a Rescuezilla v1.0.6 USB stick using the YUMI multiboot software no longer works](https://sourceforge.net/p/redobackup/discussion/help/thread/3a85949941/).

Rescuezilla v1.0.6 64-bit version is based on Ubuntu 20.04, while Rescuezilla v1.0.6 32-bit continues to be based on Ubuntu 18.04 like Rescuezilla v1.0.5.1.

While it's recommended all users create Rescuezilla USB sticks using balenaEtcher, supporting YUMI multiboot makes sense.

It's likely that Rescuezilla v1.0.6 32-bit still works (I will investigate).

**Comment by compicat** [comment]
Hi Shasheene,

Hope you are well. I ve made new tests and actually saw that 1.0.6 is also working with Yumi if you add it as "Unlisted iso with Grub (4th Partition)". Because it has grub instead of symlinux at new release, it is not working on multiboot programs if you add it as Redo Backup as before. It should be added as "Unlisted Grub ISO (4th Partition)". I can this is not an issue anymore. Other slow reboot/shutdown with 64 bit version is still exists. Thanks.

**Comment by candrapersada** [comment]
or use Yumi alternatives, [Ventoy](https://www.ventoy.net/)
Ventoy is an open source tool to create bootable USB drive for ISO files. With ventoy, you don't need to format the disk again and again, you just need to copy the iso file to the USB drive and boot it. You can copy many iso files at a time and ventoy will give you a boot menu to select them. Both Legacy BIOS and UEFI are supported in the same way. 260+ ISO files are tested.
A "Ventoy Compatible" concept is introduced by ventoy, which can help to support any ISO file.
![image](https://user-images.githubusercontent.com/36833664/85516547-82f0fd00-b628-11ea-8830-db458afe3256.png)

**Comment by shasheene** [comment]
I have seen Ventoy, but I won't be officially encouraging its use for Rescuezilla until I have chance to audit the source code, or at least have read an independent audit.

**Comment by shasheene** [comment]
I have seen Ventoy, but I won't be officially encouraging its use for Rescuezilla until I have chance to audit the source code, or at least have read an independent audit.

There's been a number of [security](https://citizenlab.ca/2020/04/move-fast-roll-your-own-crypto-a-quick-look-at-the-confidentiality-of-zoom-meetings/) [flaws](https://citizenlab.ca/2020/04/zooms-waiting-room-vulnerability/) in Zoom, discussion of Huawei routers being a major security risk in the theft of commercial data, ability for TikTok and other apps to turn on a user's microphone/camera etc. Users should be wary of using any software, but everybody should be especially careful before using Made in China software due to some systematic well-known issues.

Ventoy is open-source -- so I would be happy to recommend it _after_ somebody makes an independent security audit and gives the application the greenlight.

But until then, I would recommend any users considering using Ventoy to tread very carefully.

**Comment by shasheene** [comment]
I have seen Ventoy, but I won't be officially encouraging its use for Rescuezilla until I have chance to audit the source code, or at least have read an independent audit.

There's been a number of [security](https://citizenlab.ca/2020/04/move-fast-roll-your-own-crypto-a-quick-look-at-the-confidentiality-of-zoom-meetings/) [flaws](https://citizenlab.ca/2020/04/zooms-waiting-room-vulnerability/) in Zoom, Huawei routers frequently cited as a major security risk in the theft of commercial data, ability for the TikTok application, DJI drone or HikVision security camera to turn on a user's microphone/camera. Users should be wary of using any software, but everybody should be especially careful before using Made in China software in particular, due to some systemic well-known issues including the infamous "article 7" of China's National Intelligence Law. Combined with China's extensive and continuing track record with using all possible methods to steal commercial data, I'd recommend users tread carefully.

That said, Ventoy is open-source -- so I would be happy to recommend it _after_ somebody makes an independent security audit and gives the application the greenlight.

But until then, I recommend any users considering using Ventoy to tread very carefully.

**Comment by compicat** [comment]
Hi Shasheene,

Yumi has released new updates. Now, Rescuezilla seems as another project than Redo in Yumi and you can directly install and use it under "system tools" menu without any issue. Just wanted to let you know.

**Comment by shasheene** [comment]
Awesome! Thanks for letting me know, I hadn't yet had a chance to revisit this! I just [checked](pendrivelinux.com/yumi-multiboot-usb-creator/) it and you're completely correct:

```
YUMI UEFI Changelog

06/29/20 Version 0.0.2.3: Update to support Rescuezilla, Q4OS, and POP!OS
```
```
YUMI UEFI Download and Changelog:
June 29, 2020 YUMI-UEFI-0.0.2.3.exe: Update to support Rescuezilla, Q4OS, and POP!OS.

Legacy YUMI Download and Changelog:
June 27, 2020 YUMI-2.0.7.1.exe: Update to support Q4OS, Rescuezilla, and newer Memtest86+ 5.31. Correct grub partition 4 Warning to read "Fourth partition table entry is not empty".
```

I'll update the bug advisory page telling users to use the latest Yumi!

Thanks again!

**Comment by mzky** [comment]
> 或者使用 Yumi 替代品，[Ventoy](https://www.ventoy.net/)
> Ventoy 是一个开源工具，可以为 ISO 文件创建可启动的 USB 驱动器。使用ventoy，您无需一次又一次地格式化磁盘，只需将iso文件复制到U盘并启动即可。您可以一次复制多个 iso 文件，ventoy 将为您提供一个启动菜单来选择它们。Legacy BIOS 和 UEFI 都以相同的方式受支持。测试了 260 多个 ISO 文件。
> Ventoy 引入了“Ventoy Compatible”概念，可以帮助支持任何 ISO 文件。
> ![图像](https://user-images.githubusercontent.com/36833664/85516547-82f0fd00-b628-11ea-8830-db458afe3256.png)

This is a late reply, when not talking about politics, this tool is excellent and has been tested with RescureZilla -1.0.6.1-64bit. ISO
![image](https://user-images.githubusercontent.com/13345233/120152620-43f7fe00-c220-11eb-8dd2-cc990488ce0f.png)

**Comment by shasheene** [comment]
Yep, a lot of people do use Ventoy with Rescuezilla and I haven't heard of any issues so far.

Just make sure you don't use Rescuezilla v1.0.6 but always use the latest version!

**Comment by duven87** [comment]
me never boots with ventoy. Just ask for language and it stays black, with grub, grub2 and failover mode for graphics.
My laptop its old, a Inspiron N411Z

**Comment by shasheene** [comment]
@duven87 does the Rescuezilla v2.4.2 build titled 'Focal' work on your system? It's an older kernel so may have different support to the default build.

You can find it at the bottom of the releases page https://github.com/rescuezilla/rescuezilla/releases under the 'Assets' section.
