### ISSUE TITLE
Can't select destination disk on a virtual machine under VMware

### ISSUE THREAD

**Issue by milepost183** [rescuezilla/rescuezilla#97]
I'm using Linux version 1.06, 64-bit version. Steps to reproduce:

1. Add a virtual disk to the vm, make it the same size as virtual disk to backup
2. Boot Rzilla from the release .iso file using the vm's CD drive instead of the vm's boot disk
3. Pick vm's boot disk as source, choose all partitions
4. In Rzilla Step 3 (Select Destination Drive) choose Connected directly to my computer
5. The field "Select Destination Drive:" is not editable nor does anything appear there.

![CantSelectionDestination](https://user-images.githubusercontent.com/32940732/85335654-8eaeb900-b49a-11ea-88f4-26591ae7cb75.jpg)

Both disks are visible in the Disk utility, the destination is /dev/sdb:

![BothDiskVisible](https://user-images.githubusercontent.com/32940732/85336042-39bf7280-b49b-11ea-871c-11beae7062aa.jpg)

**Comment by shasheene** [comment]
@milepost183,

Did you create a filesystem on the destination disk? As per the [Rescuezilla limitations](https://github.com/rescuezilla/rescuezilla/wiki/Rescuezilla-Limitations):

> Rescuezilla only supports "imaging" (what Clonezilla calls "device-partition" mode), it does not support "cloning" (what Clonezilla calls "device-device" mode). In other words a backup operation copies your harddrive to files needing to be stored on a hard drive at least temporarily before it can be restored. (now captured as its own task #47) (this will be fixed in Rescuezilla v1.0.7)

**Comment by milepost183** [comment]
Mea culpa, I did not. Let me do that and retry the operation.

**Comment by milepost183** [comment]
I created an ext4 file system on the second drive and the backup worked as expected. Thanks for pointing out my error.

**Comment by shasheene** [comment]
While Rescuezilla doesn't support cloning operations yet, the user experience of this common use case could definitely be improved to make this more clear.
